### ISSUE TITLE
collapse unique and value_counts server messages 

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1022]
collapse unique and value_counts server messages because they are duplicative.
I think value_counts has all the functionality.
the only reason not to do this may be performance but I don't think so on the surface.

**Comment by Ethan-DeBandi99** [comment]
I reviewed the code related to this issue. `UniqueMsg.chpl` handles the processing of `value_count` and `unique` messages. `value_countsMsg()` does not appear to be used because no messages with `cmd="value_count"` are sent. `uniueMsg()` has the additional processing to handle returning the counts of the unique values. It appears that we could go ahead and remove `value_countsMsg()` and remove it from the register function.
