### ISSUE TITLE
Operations that localize string segments run slow with poorly distributed data

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#1059]
Regex operations and string hashing both use `lowLevelLocalizingSlice` to pull each string's bytes onto the locale where its segment pointer resides, in order to compute a function locally over those bytes. This approach works fantastically when most strings' bytes live on the same locale as their segment pointers, which is true for most arrays of strings. However, users have run into several degenerate data distributions where the majority of bytes are on different locales than their corresponding segment pointers. In these cases, the current approach is very slow because it's doing individual GETs for most of the string bytes.

One of these degenerate cases that crops up somewhat frequently is when you have an array of strings that are sorted by length. In this case, it is virtually guaranteed that a majority of bytes will live on a different locale than their segment pointers. In one such instance, a large array like this took about 20 minutes just to hash, but when we randomly permuted the same array (thus breaking the degeneracy), hashing took only a few seconds. A couple other users have mentioned running into this same type of problem.

In light of these examples, I'm about to put in a draft PR that demonstrates a different approach, in which the computation of the function (e.g. sipHash) on a given string happens on the locale where the bytes start, rather than the locale where the segment pointer resides.

We can also use this issue to propose other approaches and discuss their merits.

**Comment by ronawho** [comment]
👍  Very interested in seeing the draft PR and good to know about this issue. We discussed this a bit in https://github.com/Bears-R-Us/arkouda/issues/266, but at the time I think we decided to wait for this to be an issue in user runs and sounds like we have that now.

Like you said, today we distribute work based on the segments array and the localize any remote data. Sounds like you want to distribute work based on the data and then maybe we have a PUT the results back since the result array has the same distribution as the segments. ​This should definitely be faster though I imagine there will be some difficulties to localize strings that cross locale boundaries. I also don't expect performance to be perfectly uniform in this case because for instance the rate of SipHash is faster for larger strings so the locale that owns the large strings will likely finish faster. This should still be way better than what we have today, but is something to be aware of.

>  In these cases, the current approach is very slow because it's doing individual GETs for most of the string bytes.

Nit, but `lowLevelLocalizingSlice` should do a single GET for all bytes in a string and not a GET per byte. This will still be slow, but it's not completely fine-grained. I'm not sure that you said otherwise, but just wanted to clarify in case anybody reading at home assumed it was element at a time GETs.

**Comment by reuster986** [comment]
The solution you came up with back in #266 was a game-changer and exactly what we needed at the time. I think it's a testament to your work that it's taken us about 2 years to find the anticipated edge case where performance takes a noticeable hit!

> ​This should definitely be faster though I imagine there will be some difficulties to localize strings that cross locale boundaries.

My PR punts on this question and reuses `lowLevelLocalizingSlice` for these strings, relying on the fact that there can be at most `numLocales - 1` of them. It's still possible for this to be very slow, but it would require an array dominated by one or a few extremely long strings. So the new PR doesn't completely solve the problem, but I think it does significantly shrink the space of problem cases. 

> Nit, but lowLevelLocalizingSlice should do a single GET for all bytes in a string and not a GET per byte. This will still be slow, but it's not completely fine-grained. I'm not sure that you said otherwise, but just wanted to clarify in case anybody reading at home assumed it was element at a time GETs.

Ah, I had forgotten this -- thanks for the clarification!
