### ISSUE TITLE
File I/O Inconsistencies

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1328]
When working issue #1324, I noticed some inconsistencies with File I/O between Parquet and HDF5. I have listed them out below. I spoke with @mhmerrill and we believe that both should function as HDF5 does

- HDF5 is able to be saved with or without a file extension using the `save()` or `save_all()` methods. Parquet files always have `.parquet` appended when writing the files in `ParquetMsg.chpl`. 
- Loading HDF5 is configured so that loading is done by passing a `prefix_path` and then using `os.path.splitext()` to get the prefix and then extension and use those to load the file. This would allow `load()` to work with Parquet when doing something like `load('path_to_dir/name_prefix.parquet')`. However, when saving, the user does not have to provide the `.parquet `so this is not exactly clear when loading.
- Adding the `file_format` variable for loading requires HDF5 to retain the same functionality that was there before and then if it is set to `file_format='Parquet'` the extension must be set to `.parquet`. I have a solution doing this that I will be pushing a PR for shortly. I will link that once it is up.

I may not be aware of some reasoning behind configuring things to work this way. Is there a reason that we have this variance or can we go ahead an update the Parquet support to be more in line with the flexibility of HDF5?

**Comment by bmcdonald3** [comment]
No, the adding of the `.parquet` was totally arbitrary. At one time in history, I believe the HDF5 files were saved with a `.hdf` extension (there were, and probably still are, some documentation showing that is how they are saved), but of course they aren't today.

I would be fine with removing the `.parquet` for writing parquet files. Mostly I just liked it because I could distinguish easier between an HDF5 and Parquet file that was written with Arkouda, but I'm not sure if anyone else has an opinion on this.

**Comment by reuster986** [comment]
@Ethan-DeBandi99 I agree with the proposed updates to unify HDF5 and Parquet behavior.

**Comment by Ethan-DeBandi99** [comment]
10-4 I will get on that. Thanks!

**Comment by Ethan-DeBandi99** [comment]
Issue #1331 has been added to align the behavior of parquet with HDF5.
