### ISSUE TITLE
Arkouda Categoricals do not have a .dtype attribute

### ISSUE THREAD

**Issue by Ujustwaite** [Bears-R-Us/arkouda#1374]
Arrays and Dataframes containing Categorical objects do not support the .dtype attribute. While this is likely related to the lack of a corresponding underlying numpy datatype for Categorical objects, the lack of the dtype attribute causes difficulty, particularly when performing operations on ak.DataFrame objects when trying to determine operations appropriate for individual columns. 

Code to replicate: 

`ak.Categorical(ak.array(['see','felix','run'])).dtype`

produces output: 
```

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-579dfd5cb717> in <module>
----> 1 ak.Categorical(ak.array(['see','felix','run'])).dtype

AttributeError: 'Categorical' object has no attribute 'dtype'
```

**Comment by reuster986** [comment]
The `pandas.CategoricalDtype` class is interesting. I can definitely see why it would be useful, but also not trivial for us to implement. This gets to the question of what a dtype should represent. Should the dtypes of two Categoricals with different categories compare equal? 

It does feel like we have several levels of "type" semantics in arkouda now:
- The Chapel elemental type (int, uint, real, uint(8))
- The numpy-esque elemental dtype (np.int64, np.uint64, np.float64, np.bool, np.str_)
- The pandas-esque object type (arkouda class name, like Strings, Categorical, IPv4)

Some classes have more than one of the Chapel/numpy types, e.g. Strings has int segments and uint(8) bytes, and Categorical has np.str_ categories (itself with int segments and uint(8) bytes) and np.int64/int codes.

One idea would be to have every arkouda class implement both `.dtype` and `.objtype`, with the following semantics:
- `.dtype` is the numpy dtype of a single element of the array, e.g. what numpy dtype would `x[0]` have? This is limited to `{np.int64, np.uint64, np.float64, np.bool, np.str_}`. For example, a Categorical would have dtype `np.str_` because single element access returns a string.
- `.objtype` is the logical, human-understood type of the whole array, e.g. `pdarray`, `Strings`, `Categorical`, `IPv4`.

I think we would need to poll the user community on a proposal like this, to see if it would fit with the way people use dtypes.

**Comment by Ethan-DeBandi99** [comment]
@mhmerrill, @reuster986 - At one point in conversation it was mentioned that we should conform to pandas here. I think doing that or moving forward with @reuster986 suggestion above would be fine. Is there a preference so that we can get this updated for `Categorical`?

**Comment by Ethan-DeBandi99** [comment]
@reuster986 - This is an issue that is popping up more and more. Can we use `Categorical` as a trial implementation? There are a lot of spots in the code where we are running `.dtype` on objects that can be categorical. 

I would suggest we use this as a tracking ticket and add individual tickets for updating each class.

**Comment by reuster986** [comment]
Yes, let's go ahead and use `Categorical` as a trial implementation for my proposal above, i.e. `Categorical.dtype = np.str_` and `Categorical.objtype = 'Categorical'`.
