### ISSUE TITLE
DataFrame Display Server-Side Performance Issue

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1398]
@ronawho ran the benchmark to test `_get_head_tail_server`'s performance. The results are

```
numLocales = 16, N = 160,000
  _get_head_tail_server Average time = 14.2314 sec
  _get_head_tail_server Average rate = 0.00 GiB/sec
  _get_head_tail Average time = 3.1467 sec
  _get_head_tail Average rate = 0.01 GiB/sec
```

This is much worse performance than we were hoping for. This initial issue was #1300.

**Comment by ronawho** [comment]
Adding some subtimers to the client on 16-node-cs-hdr I see:

10.7s on the actual server call:

https://github.com/Bears-R-Us/arkouda/blob/aba0b4149cf37767635531096d8fa62132bd61a5/arkouda/dataframe.py#L550-L551

0.65s creating `df_dict`: 

https://github.com/Bears-R-Us/arkouda/blob/aba0b4149cf37767635531096d8fa62132bd61a5/arkouda/dataframe.py#L554-L567

and 0.3s in the `to_pandas` call:

https://github.com/Bears-R-Us/arkouda/blob/aba0b4149cf37767635531096d8fa62132bd61a5/arkouda/dataframe.py#L571


Digging into the server call, I found most of the time was spent localizing the segments in `df_seg_array_idx`:

https://github.com/Bears-R-Us/arkouda/blob/aba0b4149cf37767635531096d8fa62132bd61a5/src/DataFrameIndexingMsg.chpl#L77-L82

---

What I'm seeing is that most segments were of len 5, but one was of len 799500, and gathering that one is where al the time is going. This is because orig_segs looks like:


> 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 799750 799755 799760 799765 799770 799775 799780 799785 799790 799795 799800 799805 799810 799815 799820 799825 799830 799835 799840 799845 799850 799855 799860 799865 799870 799875 799880 799885 799890 799895 799900 799905 799910 799915 799920 799925 799930 799935 799940 799945 799950 799955 799960 799965 799970 799975 799980 799985 799990 799995

And in the middle we end up doing `799750 - 250` because we're subtracting segments from the beginning and the end of the array. Changing this to just not grab the middle element with the following seems to work, but I'm not sure if this is generally the right solution (and I'm not sure this is right for both even and odd sized arrays)

```chpl
        const high = orig_segs.domain.high;
        const mid = high/2;
        forall (i, os, l) in zip(orig_segs.domain, orig_segs, lens){
            if(i == high) {
                l = values.size - os;
            } else if(i == mid) {
                l = 0;
            } else {
                l = orig_segs[i+1] - os;
            }
        }
```


With this change, the execution time drops from 14.4s to 1.2s, where in the subtimers I see 0.45s on the server call and 0.65s still building `df_dict`. This can probably be optimized more, but I think it'd be worth starting with this improvement and then re-evaluating.

And just a misc note -- if I have time I'll probably take a look at the original code to see if we can make that faster. The optimized version adds a fair amount of code and I found myself wondering if we can improve the speed and scalability of the naive approach.

**Comment by Ethan-DeBandi99** [comment]
@ronawho - I tested this with even and odd sized arrays and it appears to be working. I am going to push up the recommended changes so that we can benchmark it.

**Comment by Ethan-DeBandi99** [comment]
Reopening this because @ronawho believes that there are more improvements that can be made.

**Comment by ronawho** [comment]
Going to have @bmcdonald3 take a look at this during our next sprint

**Comment by ronawho** [comment]
This was improved by some scan optimizations made to Chapel for 1.27 and by Ben's work in https://github.com/Bears-R-Us/arkouda/pull/1537. On 16-node-cs-hdr this is down to around 0.8s.

I was exploring where the remaining time is going in https://github.com/Bears-R-Us/arkouda/pull/1579 and it looks like most of it is creating SymEntry's and the distributed domains/arrays that back them. Here's the current break down I see:

```
 segPdarrayIndex     : 0.89s
     getSegString1   : 0.00s
     strings[iv.a]   : 0.50s
     getSegString2   : 0.32s
              checks : 0.04s
        gather bound : 0.11s
      len and offset : 0.06s
 gatheredVals create : 0.09s
              gather : 0.07s
```

Where it's not super clear from that what all is a subtimer, but basically the total time is ~0.9s with ~0.5s going to `var (newSegs, newVals) = strings[iv.a, smallIdx=smallIdx];` and ~0.3s going to `var newStringsObj = getSegString(newSegs, newVals, st);` (and the others are subtimers of `strings[iv.a]`)

`getSegString` is just taking 2 existing distributed arrays and stashing them into SymEntry's and I was surprised how much time that took and a fair amount of the time in `strings[iv.a]` is also in array creation.

I've created a few upstream issues to improve array creation. https://github.com/chapel-lang/chapel/issues/20197 is about making distribution/domain/array creation faster, https://github.com/chapel-lang/chapel/issues/20167 is about being able to cache domains so we can avoid recreating the same domain so many times, and https://github.com/chapel-lang/chapel/issues/20164 discusses some additional overheads of then storing these distributed arrays in a class.

**Comment by ronawho** [comment]
Array creation has been optimized upstream in https://github.com/chapel-lang/chapel/pull/20241 and https://github.com/chapel-lang/chapel/pull/21038. SymEntry creation overhead was reduced in https://github.com/Bears-R-Us/arkouda/pull/1921

Dataframe display is now down to ~0.35s on [16-node-cs-hdr](https://chapel-lang.org/perf/arkouda/16-node-cs-hdr/?startdate=2022/10/11&enddate=2022/11/27&configs=release,nightly&graphs=dataframedisplayperformance):

![image](https://user-images.githubusercontent.com/1588337/204629478-3938eaa3-4ebe-4c43-b5e6-ab7c51981225.png)

There's no other obvious low-hanging optimization opportunities that I'm aware of, so I believe this can be closed since we're well below the 1s goal from https://github.com/Bears-R-Us/arkouda/issues/1300.
