### ISSUE TITLE
short term fix for LONG CI times

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#1417]
for the short term we are going to remove the multi-locale testing from the CI.
CI times have grown to over 1 hour.

**Comment by bmcdonald3** [comment]
Just wanted to mention that, for developers who do not have any easy way to run multi-locale testing on their machines, the CI can be the easiest way to do that.

If the only machine you have access to is your laptop, it can be a real pain to switch your whole environment to gasnet just to run the tests on that branch since it can cause headaches in your environment and things like that.

Probably just reflecting poor development practices on my part, but sometimes if I am making a small change or something I will depend mostly on the CI testing for the multi-locale testing because of the overhead to build on my machine.

With this change, any multi-locale failures would come through on Chapel nightly testing, which may be a bit difficult for developers outside of the team to get the information relayed to them and only then do the first gasnet builds and then presumably needing to pass that information back to the Chapel team to check before calling it good.

I think this is more of an outlier case though, since the vast majority of PRs do not have make any difference if it is in gasnet or comm=none, so I am overall in favor of doing this I would say.
