### ISSUE TITLE
Advanced indexing in `ArrayView`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1738]
Part of #1335 

Add [Advanced Indexing](https://numpy.org/doc/stable/user/basics.indexing.html#advanced-indexing) to `ArrayView` and handle the special case when [mixing advanced and basic indexing](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d) with non-consecutive advanced coordinates

**Comment by Ethan-DeBandi99** [comment]
@pierce314159 - leaving my thoughts here from the article you sent Friday ([Linked Here for Context](http://web.mit.edu/dvp/Public/numpybook.pdf)). Based on chapter 3.4, it seems to be fairly similar to the previous article in nature. I think here we have a better layout of specific cases when each indexing type occurs and things to ensure are true. Based on our previous discussions I thought most of this was handled. 

My suggestion would be layout each individual edge case. If we can combine later, great. I think it is more important to get each case working first. From there, let's focus on each case individually and ensure proper functionality before moving on to the next.

I would also like to bring up a question that concerns me. The way NumPy advanced indexing works is not at all intuitive. As a result, I worry that many users would feel the results may be wrong because intuitively it is not always what you would expect. Because of this, I think we should discuss a potential deviation from NumPy to what intuitively makes sense OR need to document this indexing in a way that makes it crystal clear for any user to follow. Additionally, I believe we need to document this in a way that any developers would understand (whether separate or the same as user docs) for continued maintenance and longevity.

**Comment by Ethan-DeBandi99** [comment]
We are currently investigating another implementation of multi-dimensional arrays within Arkouda. For now, all work on ArrayView is on hold.

**Comment by Ethan-DeBandi99** [comment]
This implementation is being deprecated in favor of Array API
