### ISSUE TITLE
Multi-column Parquet write inefficiencies

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#1876]
Passing along a comment from another developer. " I've noticed that Parquet output from Arkouoda is currently very slow. The Arkouda client library saves multi-column dataframes by sending a separate writeParquet request to the server for each column, adding them to the file one-by-one. The ccp_appendColumnToParquet function doesn't add the column to the file in-place, though; instead it loads the whole existing file into memory, adds the new column to the table object in memory, and overwrites the whole file with the new version. That means it's loading and re-saving the content of all the old columns each time it adds a new one, which adds a lot of overhead since this happens for every column."

**Comment by bmcdonald3** [comment]
Thanks for bringing this issue to our attention. When the Parquet work was implemented, it was before the dataframe functionality had been implemented, so that use case wasn't considered in the initial design. As you have seen, the Parquet append functionality is very sub-optimal and that is because Parquet does not support appending to files natively, so we had to work around that by reading in the whole file and then rewriting it.

I do not have a great deal of familiarity with the dataframe code as it exists today, but I suspect that we should be able to implement a much faster implementation that only writes to the file once. I hope to get to this in the near future.

**Comment by 21771** [comment]
Thank you!

**Comment by Ethan-DeBandi99** [comment]
Spoke with @bmcdonald3. To allow me to get more familiar with the Parquet code, I am going to take this one.

**Comment by Ethan-DeBandi99** [comment]
@21771  - Just wanted to provide an update on this. I have made good progress and have things working for single locale runs. However, I am still working out some things on distributed systems. I am hoping to have things wrapped up soon.
