### ISSUE TITLE
Support `%` with floats

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1939]
Adding an issue to track adding `%` and `%=` functionality for floats. This isn't currently supported in chapel main (see comments in PR #1930), but it is possible in numpy so we should support it as well
```python
>>> f = np.array([3.5, 0.4, 9.7])
>>> f %= np.uint(3)
>>> f
array([0.5, 0.4, 0.7])

>>> f = np.array([3.5, 0.4, 9.7])
>>> f %= 2.3
>>> f
array([1.2, 0.4, 0.5])
```

**Comment by ronawho** [comment]
While `%` is not currently defined for `real`s in Chapel, you should be able to use [`mod`](https://chapel-lang.org/docs/modules/standard/AutoMath.html#AutoMath.mod).

**Comment by bradcray** [comment]
FWIW, we have had other users who have requested supporting % and %= on Chapel reals, mapping them to `fmod()` under the covers.  The current/previous implementation of `%` definitely did nothing reasonable like that, though.  For example, see https://github.com/chapel-lang/chapel/issues/19255 and discussions on https://github.com/chapel-lang/chapel/issues/6205 (which seems to suggest I was at one time well-aware that `%` on reals was broken?!?).  All that said, if `fmod()` is what you want, Elliot's correct that you could map to Chapel `mod` in the server for the time being (or even forever?).

One thing to be slightly careful of is what the expected behavior is for negative values in either operand.  I've got to imagine NumPy also uses `fmod` under the covers, so would expect it to match but if you want to ensure parity, it would be good to check such cases.
