### ISSUE TITLE
Investigate adding back `twoReturnComputeOnSegments` for small str groupby optimizations

### ISSUE THREAD

**Issue by stress-tess** [Bears-R-Us/arkouda#1955]
Look into adding back `twoReturnComputeOnSegments` that was stripped out in #1869

**Comment by ronawho** [comment]
Instead of using two-arrays, I wonder if you could instead return an array of `uint(16)` tuples like we do for `coargsort`. In the coargsort case we merge multiple input arrays into a single array of `uint(16)` tuples and then call sort on that and I wonder if that could help here (in that you only need a single array instead of two and you could probably have similar code used for 64-bit and 128-bit strings without having to change the implementation much.)

For reference https://github.com/Bears-R-Us/arkouda/pull/330 was the original implementation of the merged coargsort. And note that `uint(16)` is the digit size for sort, which is why that was chosen. If working with `uint(8)` would simplify how you copy string bytes over we could also add sort support for `uint(8)` values.
