### ISSUE TITLE
Review `autoapi` Documentation Configuration

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1987]
Complete after PR #1985 has been merged.

Most of the `autoapi` generated documents are in `pydoc/usage`. These files need to be reviewed to ensure

- Nothing Crucial is missing
- Nothing is outdated

**Comment by Ethan-DeBandi99** [comment]
Users have reported that there are in fact missing pieces of information. These need to be tracked down. 

**Another Note** - The usage section seems to have a lot of duplication from the API Reference. We should either retool this to link to the API instead of recreating it for some functions in the Usage section and make sure the information is up to date. Or remove this section. I will be adding a separate issue for this.

**Comment by Ethan-DeBandi99** [comment]
As an additional note, I have noticed that some of the rst formatting is not rendering properly in the auto-generated docs. We will need to update any occurrences of this.

**Comment by pierce314159** [comment]
I responded in slack but duplicating here for future reference,

> i like forcing devs to add something to the `__all__`. I feel like it makes ppl take a second to decide "do i actually want this to be user facing/part of the public api" rather than that being the default. This kinda helps prevent accidentally bloating our namespace with a bunch of helper funcs that should really be `_helper`
i agree that this should be equivalent provided we enforce good practices. If we go this route we'll just have to be a bit more careful in code reviews to make sure everything that shouldn't be user facing has the leading underscore. 

Ultimately I lean slightly towards option 2, just because i like having hard guardrails up and for bad code hygiene to not work rather than for us to have to catch in a review.

I think anyone following best habits should have the leading underscore for non-public functions, but the question is what happens if someone doesn't follow best practices either from lack of experience or just an oversight. With option 2, this isn't a really big deal because it's not included unless they actively decide to include it. With option 1, this now adds a function that shouldn't be user facing to our `ak.` namespace

**Comment by Ethan-DeBandi99** [comment]
Documenting the final decision on a path forward. 

- Continue using `__all__` for imports
- Adhere to the standard that private functions are of the form `_func_name`. 

Initially, we should get everything into the documentation that is needed. If any obvious helper functions need the naming updated, that should be done at this time. After this initial pass, if there is any user facing/documented code that was missed or code that should not be user facing, we should continue to add issues to ensure correctness of our documents.
