### ISSUE TITLE
Aggregation on `bigint`

### ISSUE THREAD

**Issue by pierce314159** [Bears-R-Us/arkouda#1994]
When adding functionality for `bigint` pdarrays, we are running into cases (see #1990) where we'd like to do aggregation. This doesn't work out of the box and it's unclear if it's possible to aggregate or even bit-copy `bigint`. This issue will track the investigation of adding this functionality

**Comment by ronawho** [comment]
Haven't thought about this deeply, but there are two main assumptions unorderedCopy/Aggregation currently make:
 - The underlying type is trivially copyable (bits can be `memcpy`'d without any additional fixups)
 - The datatype is uniform in size. This is not generally true for bigints since something like `2**64` will require more limbs/bits than `2**1`, but if you're using bigints as a fixed with integer, maybe we can ensure the underlying gmp type has the same number of limbs.

**Comment by pierce314159** [comment]
> * The datatype is uniform in size. This is not generally true for bigints since something like `2**64` will require more limbs/bits than `2**1`, but if you're using bigints as a fixed with integer, maybe we can ensure the underlying gmp type has the same number of limbs.

I don't think the users are expecting us to treat bigints as fixed width integers, so if we are able to find a way to make this more efficient without making that restriction, that would be ideal. I can run it by them and see if fixed width would suit their needs
