### ISSUE TITLE
Parquet Read SegArray with Empty Segments

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2145]
The current implementation does not account for empty segments in the indexing.  The workflow for reading needs to be updated to properly increment past the empty segment.

**Comment by pierce314159** [comment]
I have an idea for accounting for the empty segments. I might be way off here, so please let me know if im misunderstanding anywhere

So we are writing the segment lengths on a delay because we don't know if we're at the end of a segment until after the fact (when `rep_lvl==0`, the previous value was a segment end. And the last value `!int_reader->HasNext()` is always a segment end)

It seems the issue with empty segments is they should be treated as segment ends, but it's hard to tell between them and the very first value (because in both cases `rep_lvl == 0 && seg_size == 0`). I think the trick here is that since we are writing into segment sizes on a delay, we never want to write into it on the first element (because that would mean the previous value was a segment end, except there wasn't a previous value). So i think just having a bool will solve that issue

i *think* we might be able to just get away with
```c++
bool first = true;
while (int_reader->HasNext()) {
  int64_t value;
  (void)int_reader->ReadBatch(1, &definition_level, &rep_lvl, &value, &values_read);
  if (values_read == 0) {
    // empty segment, so the previous value was a segment end
    // NOTE when first, this is equivalent to just `i++;`
    // since seg_size and offsets are initialized to 0
    offsets[i] = seg_size;
    i++;
    seg_size = 0;
  } else {
    if (!first && rep_lvl == 0) {
      // rep_lvl == 0 and not first means previous value was a segment end
      offsets[i] = seg_size;
      i++;
      seg_size = 0;
    }
    // increment counters
    seg_size++;
    vct++;
  }
  if (first) {
    first = false;
  }
}
// the last value is always a segment end
offsets[i] = seg_size;
```

I think this would also work if you like this flow better
```c++
if (values_read == 0 || (!first && rep_lvl == 0)) {
  offsets[i] = seg_size;
  i++;
  seg_size = 0;
}
if (values_read != 0) {
  // increment counters
  seg_size++;
  vct++;
}
if (first) {
  first = false;
}
```
