### ISSUE TITLE
Improve aggregation ease of use

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#237]
The aggregation interface is relatively simple, but it requires using task-intents to create a per-task aggregator. There are also distinct src/dst (GET/PUT) aggregators. It would be great to have a single aggregator instead of having to hardcode src/dst. Distinct aggregators were originally done to reduce memory overhead so we only have buffers for the type of aggregation. i.e. I didn't want to allocate space for source buffers if only destination ones were needed. We should be able to automate though, we just have to defer allocation until we need it. 

It would also be nice to add a wrapper for a common case of assigning an array to the index of a different array.

e.g. currently we have to write something like:

```chpl
A = B[indexArr];
```

as:

```chpl
forall (a, idx) in zip(A, indexArr) with (var agg = newSrcAggregator(A.eltType)) {
  agg.copy(a, B[idx]);
}
```

But we should be able to create a wrapper that allows us to write this as:

```chpl
aggregatedCopy(A, B[indexArr]);
```

**Comment by ronawho** [comment]
https://github.com/mhmerrill/arkouda/pull/275#discussion_r374891653 is another place that would benefit from a general CommAggregator

**Comment by bradcray** [comment]
On chat, @ronawho, @mcdobe100, and I were noticing that in some cases that currently use an aggregator it seems as though a slice assignment could potentially now be used instead.  For example, IndexingMsg.chpl contains:

```chapel
            forall (elt,j) in zip(aa, slice) with (var agg = newSrcAggregator(t\
)) {
              agg.copy(elt,ea[j]);
            }
```

which seems like a longhand form of writing `aa = ea[slice];` (or `aa = ea[{slice}];` which unfortunately might still perform better...).  Note that slice is a range.  We were speculating whether this is code whose origins predate the bulk-transfer optimizations added in 1.20 and which might now be able to be written more cleanly without losing performance.

**Comment by mhmerrill** [comment]
@bradcray @ronawho @mcdobe100 what if the slice is strided? if the stride is bigger then this code I think is what you want. We wrote it like this because we didn't think the compiler/runtime would do the right thing.

**Comment by mcdobe100** [comment]
This is also one other case that I the aggregator works better than the slice operator would, I am not aware of anyway to do this otherwise, although it certainly may exist
https://github.com/mhmerrill/arkouda/blob/6bf11b62fbd0eec895e407559d752b86fd5da779/src/IndexingMsg.chpl#L151-L155
I think setting some sort of standard to achieve greater code uniformity throughout the code base is a good idea and one possible way we could do this is to create helper functions that use the aggregator and just call into them rather than inserting that aggregator code every time a copy is required, similar to how `makeDistArray()` is used in Arkouda currently.

If that sounds alright with you guys, I could definitely take that on as a task to remove the occurrences of the aggregator code, but am open to other ideas as well. @bradcray @mhmerrill @ronawho

**Comment by ronawho** [comment]
I haven't had a lot of time to think about this issue, but at a high level I'll note that aggregation is really important for performance, especially on non-cray networks. We should be careful about changing uses of aggregation. 

For Brad's example, I suspect we will use bulk comm for simple cases, but not if the slice is strided, but I'd need to check that. 

For the `if truth` variant, it's not clear to me what that would look like with a wrapper. And in general there's a pretty wide variety of aggregation uses in arkouda and for most of them it's not clear to me what the clean wrappers would look like yet.

I agree that the aggregators hurt code readability and am all for improving that, but I worry it's a pretty involved task.

**Comment by bradcray** [comment]
I'm fairly confident that our bulk communication does buffering for some strided cases, but I don't recall whether this was one of them (the other major case being taking a "dense" slice along an array dimension that isn't adjacent in memory, like an array column `{1..n, i}` where the array is laid out in row-major order).  But I think it ought to.  Or, put another way, I think that ultimately we want to encourage users to use array slicing to express moving regular collections of data around and to make our implementation fast for those cases (where the implementation could even translate to this aggregator pattern under the hood...?).

We know Chapel slicing isn't always fast today and that we need to continue to identify and improve cases where it isn't.  If this is one of them, it should obviously remain as-is so that Arkouda continues to perform well, but I find it a good motivator for either writing it more cleanly (if no performance is lost, to lock that in) or to focus more on this case for Chapel slicing.

Maybe as he gets ramped up on performance testing and wraps up his current tasks, @mcdobe100 could do the measurements to take stock of how these different patterns perform today?

**Comment by mhmerrill** [comment]
@ronawho can we close this?

**Comment by ronawho** [comment]
Closing, since it's tracked upstream.
