### ISSUE TITLE
Segarray write/read example

### ISSUE THREAD

**Issue by 21771** [Bears-R-Us/arkouda#2381]
**Describe the bug**
Unfortunately I'm still on 03.01, so updating is on me. But would it be possible to provide a very simple example of a write and read for a dataframe containing a segarray? Using v.03.01 would be ideal, but any later version is fine and the onus is on me to catch up.
I have not had success after v.02.08.
Thanks!

**To Reproduce**

**Expected behavior**

**Error Message**
If you are receiving any error messages, please provide them here.

**Is this a Blocking Issue**
- Are there any known work-arounds?
- If a known work around exists, please provide a code block demonstrating it.

**`ak.get_config()` Output**
Providing the output of `ak.get_config()` provides crucial debugging information.

**Additional context**

**Comment by Ethan-DeBandi99** [comment]
@21771 - the issue with saving a DataFrame containing a SegArray was resolved by the work done in PR #2337. The save was actually prohibited by the same issue. I verified that the read is functional. I verified that this is fully functional in the `v2023.04.07` release. Just for clarity, I included the python code I used for testing below. Unfortunately, the write portion is not function in `v2023.03.01`, but based on the test code below works in `v2023.03.24` and our latest release `v2023.04.07`.

```python
import arkouda as ak

ak.connect()

df = ak.DataFrame({
    'idx': ak.arange(100),
    'seg_col': ak.segarray(ak.arange(0, 500, 5), ak.randint(0, 20, 500)),
    'int_col': ak.randint(0, 25, 100),
    'str_col': ak.random_strings_uniform(0, 16, 100)
})

fpath = "/path/to/file/"
df.to_hdf(fpath+"hdf_dataframe")

hdf_data = ak.DataFrame(ak.read_hdf(fpath+"hdf_dataframe_*"))
print(hdf_data.__repr__())

df.to_parquet(fpath+"pq_dataframe")

pq_data = ak.DataFrame(ak.read_parquet(fpath+"pq_dataframe_*"))
print(pq_data.__repr__())

ak.disconnect()
```

In order to provide a work around for you for `v2023.03.01`, you can do the following:
```python
import arkouda as ak

ak.connect()

df = ak.DataFrame({
    'idx': ak.arange(100),
    'seg_col': ak.segarray(ak.arange(0, 500, 5), ak.randint(0, 20, 500)),
    'int_col': ak.randint(0, 25, 100),
    'str_col': ak.random_strings_uniform(0, 16, 100)
})

fpath = "/path/to/file/"
m = "truncate"  # unless adding full df to an existing file
for c in df.columns:
    df[c].to_hdf(fpath+"hdf_dataframe", dataset=c, mode=m)  # will also work with to_parquet
    m = "append"  # switch to append to add remaining columns
```
This code will work for saving to hdf5 and parquet, but saving to Parquet will be significantly less performant. This should hopefully get you around the issue while you are still on `v2023.03.01`. Once you are able to upgrade, you should definitely switch back to the standard workflow. If you have any further issues, please let me know.

I am going to leave this issue open for now to make sure you have seen this and are able to confirm functionality on your end.

**Comment by 21771** [comment]
Thank you!

**Comment by Ethan-DeBandi99** [comment]
No problem. I am going to close this. If anything else comes up, please let me know.

**Comment by 21771** [comment]
Thanks again. I'm looking forward to trying v2023.04.07 but currently have to use 02.08 because read performance on 03.x versions are prohibitive. Once the I/O issues are resolved there will be a request for support of strings (or categoricals).
