### ISSUE TITLE
Unexpected results from `ak.GroupBy.count()` with `Float64` containing `NaN`

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2615]
When converting `nan_test.py` to the new test framework, it was discovered that `ak.GroupBy.count()` is producing unexpected results with `NaN` values. The existing test runs `.count()` but does not validate the output.

**Output from PROTO_tests/tests/groupby_test.py:test_pandas_equivalency_nan`** 
```
[2, 5, 0, 5, 4, 3, 2, 5, 5, 2, 5, 7, 5, 2, 6, 4, 4, 1, 7, 3, 6, 7, 1, 3, 7, 6, 6, 5, 1, 7, 6, 0, 0, 7, 4, 5, 4, 7, 5, 0, 4, 1, 1, 3, 3, 0, 4, 3, 2, 2, 7, 4, 2, 7, 3, 7, 7, 2, 0, 7, 3, 0, 3, 1, 1, 7, 1, 2, 3, 7, 7, 7, 5, 6, 6, 4, 2, 5, 2, 0, 5, 4, 4, 0, 6, 3, 6, 5, 5, 3, 6, 3, 4, 2, 2, 6, 0, 3, 1, 2]
[0 1 2 3 4 5 6 7]
[ 6  8 12 11  8 12  9 10]
[0 1 2 3 4 5 6 7]
[10 9 14 14 12 14 11 16]
```

**Comment by pierce314159** [comment]
Digging into this a bit, the `nan`s don't really factor into `count` at all. This more has to do with the way we are calculating the pandas side of the count groupby aggregation than anything

`count` is just counting the keys and doesn't take in values, but we still use values in `groupby_to_arrays` in order to generate the pandas object we are comparing against. For this particular example we are passing in values which has `nan`s and that is causing the pandas object to drop those, but if we choose to pass in something different for the values (like the keys for instance), this would work just fine.

I changed the below lines in `groupby_test.py`, and that was enough to get both `test_pandas_equivalency` and `test_pandas_equivalency_nan` to pass with `count`
```python
-        g = df.groupby(kname)[vname]
+        g = df.groupby(kname)[vname] if op != "count" else df.groupby(kname)[kname if levels==1 else kname[0]]

-            akkeys, akvals = akg.aggregate(akdf["float64"], op, True)
+            akkeys, akvals = akg.count() if op == "count" else akg.aggregate(akdf["float64"], op, True)
```
But since `count` has nothing to do with the values, I don't think it's actually worth updating the test since this is already being covered in the regular `test_pandas_equivalency`. So i'm gonna close this issue
