### ISSUE TITLE
Expand Arkouda Installation Documentation for Ubuntu, GPU, and Anaconda Users

### ISSUE THREAD

**Issue by awthomp** [Bears-R-Us/arkouda#262]
When working on enabling GPU support with https://github.com/mhmerrill/arkouda/pull/248, I was able to build both Chapel and Arkouda on my Ubuntu 18.04 system and created an Anaconda environment for easy and isolated dev/testing. In the near term, I plan on:

- [ ] Document building Chapel in Ubuntu, including setting up the correct environment variables
- [ ] Create an Anaconda yml environment file with the necessary Arkouda Python dependencies and optional GPU support via Numba
- [ ] Explore grouping the Chapel + environment build with some `build.sh` script to provide a lazy install

**Comment by buddha314** [comment]
I am about to attempt to install Arkouda under the Windows Subsystem for Linux.  I would love to see some instructions there.  Also, it would be nice to see the docs hosted on a web page.

**Comment by Ethan-DeBandi99** [comment]
@joshmarshall1 recently updated the Ubuntu install documentation and everything necessary for configuration should be listed. Arkouda does not support GPU installs because Chapel does not support running on a GPU at this time. Adding a .yml file to configure the Anaconda environment is being tracked by issue #1302. Recommend closing this issue.

**Comment by mhmerrill** [comment]
i concur with closing this.
