### ISSUE TITLE
bug in sorted

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#2942]
sorted fails because it calls a function DataFrame.sort() which does not exist.  Probably it is supposed to call DataFrame.sort_values instead.  Should match the pandas implementation:

```python
from arkouda.dataframe import sorted
df = ak.DataFrame({'col1': ak.arange(5), 'col2': -1 * ak.arange(5)})
sorted(df, column="col2")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[150], line 1
----> 1 sorted(df, column="col2")

File ~/git/arkouda/arkouda/dataframe.py:4315, in sorted(df, column)
   4313     raise TypeError("The sorted operation requires an DataFrame.")
   4314 result = DataFrame(df.data)
-> 4315 result.sort(column)
   4316 return result

File ~/git/arkouda/arkouda/dataframe.py:643, in DataFrame.__getattr__(self, key)
    641 def __getattr__(self, key):
    642     if key not in self.columns:
--> 643         raise AttributeError(f"Attribute {key} not found")
    644     # Should this be cached?
    645     return Series(data=self[key], index=self.index.index)

AttributeError: Attribute sort not found
```

**Comment by pierce314159** [comment]
Nice find! After looking at git blame it seems this was added in the initial move of dataframe from akutil https://github.com/Bears-R-Us/arkouda/pull/1139/files

I expected that at some point there was a rename of `sort` to `sort_values`, but surprisingly it seems that it was broken from the beginning because there's no `dataframe.sort` method defined in this PR either. I'm pretty shocked no one has encountered this until now
