### ISSUE TITLE
Arkouda crash on argsort

### ISSUE THREAD

**Issue by hokiegeek2** [Bears-R-Us/arkouda#3089]
**Describe the bug**
ak.argsort _appears_ to crash Arkouda with an uncaught OOM, first producing the message below followed by an arkouda_server crash:

```
projected memory use of 77%
```

Also, the radixSortLSDCore invocation within the ak.DataFrame.groupby  _appears_ to crash Arkouda with an uncaught OOM, first producing the message below followed by an arkouda_server crash:

```
projected pct memory used of 84%
```

**To Reproduce**
Steps to reproduce the ak.argsort behavior:
1. export CHPL_RT_NUM_THREADS_PER_LOCALE=3
2. ./arkouda_server -nl 6 --logLevel=LogLevel.DEBUG memMax=12000000000,  --ServerDaemon.daemonTypes=ServerDaemonType.DEFAULT,ServerDaemonType.METRICS
3. Load a 1-D array with the following attributes: 
`'[{"name":"<array name>", "dtype":"int64", "size":1393000000, "ndim":1, "shape":[1393000000], "itemsize":8, "registered":false}]'`
4. ak.argsort(pd)
6. Logging stops, for AOS squeue shows Arkouda job has stopped

Steps to reproduce the ak.groupby behavior:
1. export CHPL_RT_NUM_THREADS_PER_LOCALE=3
2. ./arkouda_server -nl 6 --logLevel=LogLevel.DEBUG memMax=40000000000,  --ServerDaemon.daemonTypes=ServerDaemonType.DEFAULT,ServerDaemonType.METRICS
3. Load a 1-D array with the following attributes: 
`'[{"name":"<array name>", "dtype":"int64", "size":2786000000, "ndim":1, "shape":[2786000000], "itemsize":8, "registered":false}]'`
4. dft = {'<column name>', pdarray}
5. df = ak.DataFrame(dft)
6. df.groupby(keys=['<column name>').count()
7. Logging stops, for AOS squeue shows Arkouda job has stopped

**Expected behavior**
Should get overMemLimit error

**Error Message**
logging stops

**Is this a Blocking Issue**
Not sure how widespread this error is potentially, but it's a very popular command

**Comment by ShreyasKhandekar** [comment]
Hi John, 
I've been able to reproduce this issue with your parameters and I'm looking into a solution.
Could you let me know what version of Chapel you're using?

**Comment by hokiegeek2** [comment]
@ShreyasKhandekar Thanks for looking into this! I've been able to reproduce this w/ 1.3[2-3] and 2.0.0

**Comment by ShreyasKhandekar** [comment]
Hello @hokiegeek2 

I was able to track down what is going on here and resolve the issue. If you want to see what was causing the crash check out https://github.com/chapel-lang/chapel/issues/25005.

I have https://github.com/Bears-R-Us/arkouda/pull/3163 which should resolve this with a workaround.

I also wanted to make sure you're setting `CHPL_GASNET_SEGMENT=fast`. This is because the `tryCreateArray` interface which is used by `makeDistArray` is most reliable in configurations that use a fixed heap (like `CHPL_GASNET_SEGMENT=large` or `CHPL_GASNET_SEGMENT=fast`).

If you don't have this set, the heap size is dynamic which may or may not work. It is possible that an overcommit will cause the array allocation to succeed even in the case where the heap size is dynamic, even if there is not enough physical memory to satisfy the allocation, which will then error out when attempting to access the array.

**Comment by hokiegeek2** [comment]
@ShreyasKhandekar awesome! No, I don't set CHPL_GASNET_SEGMENT=fast and neither do arkouda users in general b/c that setting is not in our instructions. @stress-tess Sounds like we should add CHPL_GASNET_SEGMENT=fast to our instructions.

**Comment by stress-tess** [comment]
@ShreyasKhandekar @hokiegeek2 
Is there any drawbacks to using fixed heap / `CHPL_GASNET_SEGMENT=fast` compared to variable heap? It seems it's not terribly common. Like is that something that would be reasonable to recommend users to do in production?

I am far from an expert on this but a little bit of digging lead me to [this](https://www.ibm.com/docs/en/explorer-for-zos/3.3?topic=considerations-fixed-java-heap-size) (it's talking about fixed heap for java, but I would imagine at least some of it would be relevant)

The bit that stands out to me is:
> increases the risk of fragmentation, which requires a heap compaction

since arkouda servers tend to be long running, the risk of mem fragmentation is already quite high. So my first impression is we might have a harder time finding a chunk of memory big enough and that over the course of the life of the server the maximum array we could allocate would shrink?

Also if they're free, I'd like to get @jeremiah-corrado and @bmcdonald3's 2 cents on using `CHPL_GASNET_SEGMENT=fast`

**Comment by stress-tess** [comment]
yah i've no clue how garbage collection works in chapel so I glossed over that part lol, but the memory fragmentation issue seemed like it would still apply

**Comment by stress-tess** [comment]
awesome! That's good to know!
