### ISSUE TITLE
make fails when lib and lib64 directories are both present

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3475]
After this PR:
https://github.com/Bears-R-Us/arkouda/pull/3423

`make` fails if both `lib` and `lib64` are present and the necessary dependencies are in `lib`.  

@stress-tess @brandon-neth @bmcdonald3

**Comment by bmcdonald3** [comment]
I think I would be in favor of just going back to the old way, I'm not sure anyone else has ever encountered the error that led to #3423 when we were in that state for a couple of years, so it seems more likely to be an issue with the specific environment this was run in, rather than an issue with the build script itself... It seems unsatisfying, but I think it is hard to argue with years of never having encountering an issue and then a change causing issues very soon after, it is likely the change that is "less correct" if that makes sense.

**Comment by stress-tess** [comment]
> I think I would be in favor of just going back to the old way, I'm not sure anyone else has ever encountered the error that led to #3423 when we were in that state for a couple of years, so it seems more likely to be an issue with the specific environment this was run in, rather than an issue with the build script itself... It seems unsatisfying, but I think it is hard to argue with years of never having encountering an issue and then a change causing issues very soon after, it is likely the change that is "less correct" if that makes sense.

yah that makes sense to me! I'm up for going back to the old logic

**Comment by ajpotts** [comment]
If you're curious, here is the error I was seeing:
```
                            init :   0.001 seconds
/usr/bin/ld: cannot find -lhdf5: No such file or directory
/usr/bin/ld: cannot find -lhdf5_hl: No such file or directory
/usr/bin/ld: cannot find -liconv: No such file or directory
/usr/bin/ld: cannot find -lparquet: No such file or directory
/usr/bin/ld: cannot find -lhdf5: No such file or directory
/usr/bin/ld: cannot find -lhdf5_hl: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
error: Make Binary - Linking


```
