### ISSUE TITLE
Benchmarks for arkouda vs numpy performance

### ISSUE THREAD

**Issue by brendapraggastis** [Bears-R-Us/arkouda#41]
@mhmerrill Do you have or could you generate benchmarks indicating the performance improvement that arkouda provides over numpy?

**Comment by ben-albrecht** [comment]
Not sure if this is the right place to post this, but here are some other projects that could be interesting to compare against eventually:

- https://github.com/dask/dask
- https://github.com/apache/spark
- https://github.com/modin-project/modin

**Comment by bradcray** [comment]
Also:
* [NVIDIA's Legate](https://research.nvidia.com/sites/default/files/pubs/2019-11_Legate-NumPy%3A-Accelerated//legate-preprint.pdf)

**Comment by imdavis** [comment]
[Intel Python](https://software.intel.com/en-us/distribution-for-python) has a parallel version with MKL as the backend. I've never used this distribution of Python and I've only ever used the MKL as SMP. The [downloads page](https://software.intel.com/en-us/distribution-for-python/choose-download) says that tbb and mpi4py are "parallelism" options. [This presentation](https://www.intel.com/content/dam/www/public/us/en/documents/presentation/hpl-maidanov-seibert-python-sc-in-prod-env.pdf) discusses the use of Intel's MPI in the distribution in addition to supporting PySpark and Dask. Might be something to look into in case the question gets asked.

**Comment by bradcray** [comment]
> Intel Python has a parallel version with MKL as the backend.

This sounds to me like it's putting all of the burden back on the programmer for distributed memory runs, by forcing them back into an MPI-oriented world.  I.e., I'm not convinced it provides the productivity lift that Arkouda is for the Python programmer, nor the distributed computing productivity benefits that Chapel does.

**Comment by ronawho** [comment]
In case others are curious about concrete numbers, here are some results I gathered for arkouda vs. numpy for the tests in the benchmark directory. I ran all the benchmarks with the default problem size, which uses ~3/4 GB arrays.

The benchmarks have a `--numpy` option, but normally the arkouda server would still be running so there could be some interference for the numpy results. To make sure I got fair numpy timings, I modified the tests a little to run arkouda and numpy versions in isolation.

Arkouda is well ahead for all these benchmarks, though the specific improvement is operation dependent.

| benchmark | numpy     | arkouda   |
| --------- | --------- | --------- |
| argsort   | 32.99s    |  2.26s    |
| gather    |  2.78s    |  0.39s    |
| reduce    |  0.10s    |  0.01s    |
| scan      |  0.50s    |  0.32s    |
| scatter   |  2.54s    |  0.52s    |
| stream    |  0.59s    |  0.15s    |

These numbers were gathered on an idle 24-core server. Machine details:

<details>

Hardware:
 - 24-core (48 HT), 256 GB RAM
   - dual 12-core "Haswell" 2.6 GHz processors

Software:
 - SLES 12
 - GCC 8.3
 - Numpy 1.17.4
 - Chapel 1.20.0
 - Arkouda master (72d21d1)

</details>

If you're interested in distributed performance and scalability numbers, https://github.com/mhmerrill/arkouda/pull/231 has some results for up to 512 nodes (18,432 cores) of a Cray-XC and generally speaking scalability looks really good.

**Comment by ben-albrecht** [comment]
[Rapids](https://rapids.ai/) is another overlapping project which utilizes GPU-accelerated numpy + distribution via Dask.

**Comment by awthomp** [comment]
> [Rapids](https://rapids.ai/) is another overlapping project which utilizes GPU-accelerated numpy + distribution via Dask.

@datametrician, @kkraus14, and I would be happy to help with this comparison

**Comment by ben-albrecht** [comment]
Not a python interface, but a project with a similar functionality for single node: https://github.com/bluenote10/NimData

**Comment by ronawho** [comment]
There have been a number of scalability and scalar performance improvements to Chapel and Arkouda recently, so I regathered numbers on a Cray-XC. Below are Numpy vs. Arkouda on up to 512 nodes of a Cray-XC using 3/4 GB per node. Results are for NumPY, Arkouda run serially, Arkouda run with shared memory, and Arkouda run with distributed memory for 36 and 512 nodes. Previous results were time, but these are a rate and normalized performance (so bigger is better)

Performance (GiB/s):
---

| benchmark | numpy    | ak (serial) | ak (36-core) | ak (36-node) | ak (512-node) |
| --------- | -------: | ----------: | -----------: | -----------: | ------------: |
| argsort   |     0.03 |    0.06     |     0.50     |    7.58      |    55.12      |
| coargsort |     0.03 |    0.07     |     0.50     |    6.59      |    29.54      |
| gather    |     1.15 |    0.45     |    13.45     |   39.38      |   539.52      |
| reduce    |     9.90 |   11.66     |   118.57     | 3968.30      | 43683.00      |
| scan      |     2.78 |    2.12     |     8.90     |  136.12      |   741.14      |
| scatter   |     1.17 |    1.12     |    13.77     |  101.16      |   914.67      |
| stream    |     3.94 |    2.92     |    24.58     |  556.90      |  6266.22      |

Performance normalized to Numpy:
---

| benchmark | numpy | ak (serial) | ak (36-core) | ak (36-node) | ak (512-node) |
| --------: | ----: | ----------: | -----------: | -----------: | ------------: |
| argsort   | 1.0   | 2.0         | 16.7         | 252.7        | 1837.3        |
| coargsort | 1.0   | 2.3         | 16.7         | 219.7        |  984.7        |
| gather    | 1.0   | 0.4         | 11.7         |  34.2        |  469.1        |
| reduce    | 1.0   | 1.2         | 12.0         | 400.8        | 4412.4        |
| scan      | 1.0   | 0.8         |  3.2         |  49.0        |  266.6        |
| scatter   | 1.0   | 1.0         | 11.8         |  86.5        |  781.8        |
| stream    | 1.0   | 0.7         |  6.2         | 141.3        | 1590.4        |

Chapel serial performance for gather, reduce, scan, and stream is behind. Most of them likely because of time spent default initializing Chapel arrays. I'm not sure why serial gather is so far off though. Parallel and distributed performance are way ahead. I'd love to get some Dask comparisons too, but will likely need help collecting those.

Configuration details:

<details>

Hardware:
 - Cray XC with Aries network
 - 36-core (72 HT), 128 GB RAM
   - dual 18-core "Broadwell" 2.1 GHz processors

Software:
 - CLE 7
 - GCC 8.3
 - Cray Python 3.7.3.2
 - Numpy 1.16.4
 - Chapel 1.22.0
 - Arkouda master (06fc2a5)

</details>

**Comment by bradcray** [comment]
@mhmerrill : These Chapel vs. NumPy results from Elliot could be good fodder for the SciPy talk...

**Comment by datametrician** [comment]
@ronawho could you share the code for this? It would be nice to see how this compare to Dask/CuPy/UCX-Py

**Comment by ronawho** [comment]
I'm just using the existing public microbenchmarks in the Arkouda repo -- https://github.com/mhmerrill/arkouda/tree/master/benchmarks

There's a `run_benchmarks` script that will run all of them. e.g:

```sh
CHPL_RT_NUM_THREADS_PER_LOCALE=1 ./benchmarks/run_benchmarks.py -nl 1 --numpy # compare serial Arkouda to NumPy
./benchmarks/run_benchmarks.py -nl 1 # run parallel Arkouda
./benchmarks/run_benchmarks.py -nl 32 # run distributed Arkouda on 32 nodes
```

If you know of existing Dask/CuPy/UCX-Py benchmarks, I'd also be interested in making Arkouda ports of them.
