### ISSUE TITLE
update version and make a new tag in repo

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#508]
we've had a lot of new features added and bug fixes since we rev'd the version number.

**Comment by mhmerrill** [comment]
@glitch @hokiegeek2 @pierce314159 @reuster986 we should come up with a methodology for updating the version and tag in the repo.

Currently
- I rev the VERSION file then submit a PR
- after PR is merged into the master, I tag the commit in the commit stream which generates a release

**Comment by glitch** [comment]
Something we might want to consider is [versioneer](https://github.com/python-versioneer/python-versioneer).  The short summary is that it auto-generates the version string based on where you are in your repo.  If you create a tag in the repo the version string is based on that tag.  Depending on style (which you can configure) you can have it set as "distance" from previous tag for cases where you haven't cut a new release, you could also set it to date, etc.  The key thing is that it is generated, so there is no version file to maintain.  I'm not sure how it would splice into the chpl-side of things, but between python & make we could probably figure something out.

**Comment by reuster986** [comment]
I think the need for versioning and tagging is becoming more pronounced as we are trying to automate the building and deployment of arkouda, so I'm labeling this issue "important". I like the versioneer idea for auto-generating the version string. Our devops guy has said that he can set it up so that arkouda auto-builds whenever a new tag gets merged into master, which I think would be great, but it would require us developing some guidelines and adopting new habits around tagging.

I believe adopting an auto-versioning scheme would also make it easier for us to deploy to pypi and truly support pip installation.

@glitch if @mhmerrill is on board, would you be willing to put together a draft PR showing how versioneer would work?

**Comment by glitch** [comment]
@reuster986 You bet.  I should be able to roll something together and test it out in my fork to see/demonstrate how it works.
