### ISSUE TITLE
Is nightly 16 node correctness testing worthwhile?

### ISSUE THREAD

**Issue by ronawho** [Bears-R-Us/arkouda#807]
We do some nightly correctness and performance testing internally on a couple different systems. At times this has exposed correctness testing failures at higher node counts since nightly multi-locale testing runs with 16 nodes and CI testing only runs with 2. I think 16 nodes for performance testing makes sense, but I wanted to check if Arkouda developers thought 16 node correctness testing is worthwhile or if we should just drop down to 2 nodes for the correctness aspects. So far I don't know that we've caught anything beyond test issues from this, but if Arkouda devs find it helpful I'm happy to keep things as is. Previous examples:

 - https://github.com/Bears-R-Us/arkouda/issues/805
 - https://github.com/Bears-R-Us/arkouda/issues/721
 - https://github.com/Bears-R-Us/arkouda/issues/706
 - https://github.com/Bears-R-Us/arkouda/issues/520

**Comment by ronawho** [comment]
@mhmerrill @reuster986 @hokiegeek2 curious for your thoughts here.

**Comment by reuster986** [comment]
@ronawho I definitely think it's wortwhile to have correctness testing with 16 nodes (or at least something more realistic than 2). As you note, this testing has caught things that would otherwise have gone unnoticed until users probably found them. However, I realize it is probably annoying for you to have to personally notice these errors and manually report them back here, and it would be great to integrate that testing directly with github. Unfortunately, as I am experiencing now, the runtime of the unit tests goes way up when the number of locales is increased (for just categorical_test.py, the runtime on my laptop is 3 min on 2 locales and 21 min on 6 locales), so it probably doesn't make sense to increase the number of locales for CI. Is there a way to make github do a nightly run on 16 locales, when we wouldn't mind it taking over an hour?

**Comment by ronawho** [comment]
Sounds good, I'm happy to keep 16 node correctness testing then. It's actually not that much work for us to notice these errors and report them. We do correctness triage for our non-arkouda testing and this is a small blip compared to the rest of the testing we do. I mostly just wanted to make sure me reporting the errors was helpful and not an annoyance to you.

I don't think we can realistically bump the number of simulated locales used in github testing. The machines CI testing runs on only have 2 cores, and they already struggle to run 2 locales. I'd guess that bumping up to 16 locales would take 24+ hours to run.
