### ISSUE TITLE
Peel segfaults when delimiter is longer than last string

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#838]
Technically, it's when the delimiter is longer than the last null-terminated segment, i.e. when `length(delimiter) > length(last_string) + 1`.

**Comment by glitch** [comment]
I can't get this to segfault with a basic, but something weird is definitely going on.

This works as expected:
```python
import arkouda as ak
import pandas as pd
ak.connect("localhost")
d = "-" * 25
print(f"delimiter:{d}")
series = pd.Series([f"abc{d}xyz", f"small{d}dog", f"blue{d}hat", "last"])
print(f"series:\n{series}")
pda = ak.from_series(series, "string")
a, b = pda.peel(d)
print(f"a from peel: {a}")
print(f"b from peel: {b}")
a, b = pda.rpeel(d)
print(f"a from rpeel: {a}")
print(f"b from rpeel: {b}")
a = pda.endswith(d)
print(f"a from endswith: {a}")
```
Outputs
```
delimiter:-------------------------
series:
0      abc-------------------------xyz
1    small-------------------------dog
2     blue-------------------------hat
3                                 last
dtype: object
a from peel: ['abc', 'small', 'blue', '']
b from peel: ['xyz', 'dog', 'hat', 'last']
a from rpeel: ['abc', 'small', 'blue', 'last']
b from rpeel: ['xyz', 'dog', 'hat', '']
a from endswith: [False False False False]
```

However, when I change the series to
```python
series = pd.Series([f"abc{d}xyz", f"small{d}dog", "last"])
```
(so basically one element shorter)
The peel completely misses the second element.  Output:
```
delimiter:-------------------------
series:
0      abc-------------------------xyz
1    small-------------------------dog
2                                 last
dtype: object
a from peel: ['abc', '', '']
b from peel: ['xyz', 'small-------------------------dog', 'last']
a from rpeel: ['abc', 'small-------------------------dog', 'last']
b from rpeel: ['xyz', '', '']
a from endswith: [False False False]
```
See "a from peel" and "b from peel" second elements, it looks like it missed the delimiter.  Notice that it did NOT miss it in the 4 element case.

**Comment by glitch** [comment]
LoL, I put this in a python unit test and now the exact opposite is happening.  The array of length 3 works and length 4 misses. 🤯

**Comment by glitch** [comment]
I added some DEBUG info for the case I can get to fail (a 3 string case)
```python
>>> series = pd.Series([f"abc{d}xyz", f"small{d}dog", "last"])
>>> pda = ak.from_series(series, "string")
>>> pda
array(['abc-------------------------xyz', 'small-------------------------dog', 'last'])
>>> a, b = pda.peel(d)
>>> a
array(['abc', '', ''])
>>> b
array(['xyz', 'small-------------------------dog', 'last'])
```

```
2021-06-14:08:44:58 [arkouda_server] main Line 265 INFO [Chapel] >>> "segmentedPeel" "peel str id_7 id_8 str 1 False False True [\"-------------------------\"]"
2021-06-14:08:44:58 [MultiTypeSymbolTable] checkTable Line 230 DEBUG [Chapel] found symbol: id_7
2021-06-14:08:44:58 [MultiTypeSymbolTable] checkTable Line 230 DEBUG [Chapel] found symbol: id_8
2021-06-14:08:44:58 [SegmentedMsg] segmentedPeelMsg Line 164 DEBUG [Chapel] cmd: segmentedPeel subcmd: peel objtype: "str" valtype: "str"
 2021-06-14:08:44:58 [MultiTypeSymbolTable] checkTable Line 230 DEBUG [Chapel] found symbol: id_7
2021-06-14:08:44:58 [MultiTypeSymbolTable] checkTable Line 230 DEBUG [Chapel] found symbol: id_8
2021-06-14:08:44:58 [SegmentedArray] peel Line 517 DEBUG [Chapel] Entered peel function
2021-06-14:08:44:58 [SegmentedArray] peel Line 539 DEBUG [Chapel] i: 0, numHits[oa[i+1]]: 1, numHits[oa[i]]: 0
2021-06-14:08:44:58 [SegmentedArray] peel Line 543 DEBUG [Chapel] i: 0, hasEnough: true
2021-06-14:08:44:58 [SegmentedArray] peel Line 570 DEBUG [Chapel] We can peel, i: 0
2021-06-14:08:44:58 [SegmentedArray] peel Line 532 DEBUG [Chapel] i: 2, oa[i]: 66, D.high: 46
2021-06-14:08:44:58 [SegmentedArray] peel Line 539 DEBUG [Chapel] i: 1, numHits[oa[i+1]]: 140194507883520, numHits[oa[i]]: 1
2021-06-14:08:44:58 [SegmentedArray] peel Line 543 DEBUG [Chapel] i: 2, hasEnough: false
2021-06-14:08:44:58 [SegmentedArray] peel Line 543 DEBUG [Chapel] i: 1, hasEnough: false
```
I added debug info to the `hasEnough` section of the `forall` loop in peel and you can see from the line above (third from bottom of debug output) we have a rather _large_ number in `numHits[oa[i+a]]` and hasEnough evaluates to false... which in itself doesn't make sense since we are doing a subtraction operation to compare to the `times` variable
```
hasEnough = (numHits[oa[i+1]] - numHits[oa[i]]) >= times;
```

So now I'm even more confused.

**Comment by glitch** [comment]
I think I figured out where the (at least one of the) issues is:
https://github.com/Bears-R-Us/arkouda/blob/042d1f5780d553072f6884085c35571d7c40f35d/src/SegmentedArray.chpl#L534

When we test `hasEnough`  we attempt to look into the `numHits` array for `oa[i+1]` and `oa[i]` retrieve the values and subtract them.  However, on the second to last iteration the value of the offsets array `oa[i+1]` actually overflows the the size of the `numHits` array and presumably grabs a value at some arbitrary memory location.  Sometimes this is a big number, sometimes it is zero.  When it happens to be zero, the `>=times` operation evaluates to false which in one of my test cases is incorrect.  The overflow is possible because the `truth` array is right-truncated and is not the same size as the `values` array which is what the offsets array(`oa`) is indexing.

This _may_ also account for a seg fault depending on the underlying system / implementation? (Not sure)

**Comment by reuster986** [comment]
@glitch Good catch! I think this overflow can be avoided by changing

https://github.com/Bears-R-Us/arkouda/blob/042d1f5780d553072f6884085c35571d7c40f35d/src/SegmentedArray.chpl#L531

to 

```chpl
} else if (i == high) || (oa[i+1] > D.high) {
```

This expands the "end of array" case to cover when `oa[i+1]` would overflow `numHits`. If this case triggers, then for all subsequent iterations (if any), it is guaranteed that `oa[i] > D.high`, so we hit the first case and never the third (which has the overflow).

Side note: we would get some performance improvement by changing 

https://github.com/Bears-R-Us/arkouda/blob/042d1f5780d553072f6884085c35571d7c40f35d/src/SegmentedArray.chpl#L532

to 

```chpl
hasEnough = (numHits[D.high] + truth[D.high] - numHits[oa[i]]) >= times;
```

This would avoid a global reduction being called from a single task inside a forall, which I have a feeling is slow.

**Comment by glitch** [comment]
Ah, I'm glad you mentioned this.  I started out with setting `D` in `findSubstringInBytes` to the same length to `values.aD` and then setting the tail end of the `truth` vector to false for the length of the delimiter.  While I could verify correctness I wasn't completely happy with that solution, so I'll give the parts you identified a shot.

The good news is that I have a new chapel side unit test to help debug & confirm this issue.

One thing I was thinking bout: instead of handling the "times" component in the iteration, would it make sense to just expand the delimiter n-times?  i.e. rather than d="abc" and times=3, we could just make it "abcabcabc".  I'm not sure how big the performance impact would be, but I think it would make the code/logic a little cleaner.  I'm going to leave that aside for now and just focus on fixing the issue.  There is also a little duplicate logic in the `!hasEnough` left & keepPartial section which could be reduced, but that might make a good first issue for someone.

**Comment by reuster986** [comment]
Sounds good!

Regarding `times`, I see what you're saying, but the intent is actually to allow for non-consecutive appearances of the delimiter. For example, say we have some URLs:

```python
s = ak.array(
["www.example.com",
 "another.example.com",
 "some.ridiculously.nested.domain.underneath.example.com"]
)
```
Then you could do `s.rpeel('.', times=2)` to peel off the top two domain layers, giving you:
```python
["www",
 "another",
 "some.ridiculously.nested.domain.underneath"],

["example.com",
 "example.com",
 "example.com"]
```

I don't think we can get this functionality without the `times` logic, but I'm open to ideas.

**Comment by glitch** [comment]
Submitted [PR#850](https://github.com/Bears-R-Us/arkouda/pull/850) to address this issue.
