### ISSUE TITLE
Add mem checks for scans

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#855]
I was seeing a fair number of server crashes due to out-of-memory while performing scans, so I decided to investigate. A quick test with `benchmarks/scan.py` reveals that, on a system with 128 core, 2TB nodes, any value of `--size` above 48 billion (approx. 1/6 of available memory) will crash the server. Excluding the input and output arrays, this implies that the scan is using about 4x the input array size in working memory. @bradcray and @ronawho , does that sound right?

In any case, we should find all the scans in the source code and put in an `overMemLimit()` check, or bump the size of existing checks.

**Comment by bradcray** [comment]
Hi Bill — I would expect Chapel scans to have more like 1x-2x the memory overhead, though Elliot indicates that he wouldn't be surprised if Arkouda's model were to bump it closer to 4x.  We'll do some measurements to check.

**Comment by ronawho** [comment]
For native Chapel scans I agree with 2x overhead The result is stored into an array the same size as the input array, and there will be some extra allocations for the objects used to track state to share between tasks, but that should be minor. The `--memStats` option will report the high water mark and using that with a standalone chapel test confirms that ~2x overhead:

```
chpl test/scan/scanPerf.chpl --fast
./scanPerf --printTiming --printArray=false --n=$((10**8*4)) -nl 4 --memStats
memStats: node 0 Allocation High Water Mark: 1600011720
```


Doing something similar for arkouda but using the internal memory high water mark tracking I see memory at 3200178244 before the scan and 6400178116, which to me looks like a 4x overhead. 


```python
import sys
import arkouda as ak

ak.verbose = False
if len(sys.argv) > 1:
    ak.connect(server=sys.argv[1], port=sys.argv[2])

a = ak.ones(sys.argv[3], dtype='int64')
ak.cumprod(a)
```

```
./arkouda_server -nl 4
 python3 scan.py localhost 5555 $((10**8*4))

2021-06-24:15:06:25 [arkouda_server] main Line 412 INFO [Chapel] <<< create took 0.33780900000000003 sec
2021-06-24:15:06:25 [arkouda_server] main Line 416 INFO [Chapel] bytes of memory used after command 3200178244
2021-06-24:15:06:25 [arkouda_server] main Line 265 INFO [Chapel] >>> "set" "id_1 int64 1"
2021-06-24:15:06:32 [arkouda_server] sendRepMsg Line 168 INFO [Chapel] repMsg: {"msg":"set id_1 to 1", "msgType":"NORMAL", "msgFormat":"STRING", "user":"eronagha"}
2021-06-24:15:06:32 [arkouda_server] main Line 412 INFO [Chapel] <<< set took 7.0719789999999998 sec
2021-06-24:15:06:32 [arkouda_server] main Line 416 INFO [Chapel] bytes of memory used after command 3200177860
2021-06-24:15:06:32 [arkouda_server] main Line 265 INFO [Chapel] >>> "efunc" "cumprod id_1"
2021-06-24:15:06:32 [ServerConfig] overMemLimit Line 165 INFO [Chapel] memory high watermark = 6400178116 memory limit = 61847529060
```

**Comment by pierce314159** [comment]
I might be misunderstanding but it seems to me that arkouda scans are using 2x the memory of the input array

```python
In [3]: n = 4*(10**6)

In [4]: a = ak.ones(n, dtype='int64')

In [5]: ak.cumsum(a)
Out[5]: array([1 2 3 ... 3999998 3999999 4000000])

In [6]: 64040345/(n*8)
Out[6]: 2.00126078125
```

where I pulled the value of `64040345` from the logs

```
[arkouda_server] main Line 271 INFO [Chapel] >>> "create" "int64 4000000"
[arkouda_server] main Line 421 INFO [Chapel] bytes of memory used after command 32040041
[arkouda_server] main Line 271 INFO [Chapel] >>> "set" "id_1 int64 1"
[arkouda_server] sendRepMsg Line 168 INFO [Chapel] repMsg: {"msg":"set id_1 to 1", "msgType":"NORMAL", "msgFormat":"STRING", "user":}
[arkouda_server] main Line 421 INFO [Chapel] bytes of memory used after command 32040009
[arkouda_server] main Line 271 INFO [Chapel] >>> "efunc" "cumsum id_1"
[arkouda_server] main Line 421 INFO [Chapel] bytes of memory used after command 64040345
```

So the memory to store a single `int64` array of size `4*10**6` is `32*10**6` bytes and arkouda scan operations require 2x that in working memory with a total of `64*10**6` bytes. I think the discrepancy between native chapel and arkouda seen in @ronawho's comment is due to type differences (`int32` vs `int64`), but it's very possible I'm missing something and I appreciate any double checking

I'll go ahead and put up a PR with `overMemLimit(8*len*2);` calls before scans with `int64` arrays. I just wanted to figure out what was up to see if we could get the memory consumption for the scans on par with native chapel first

**Comment by glitch** [comment]
Just to add to @pierce314159 's example, the `cumprod` function in arkouda returns a new array of the same type & length.

So if I'm following correctly
1. The initial array is 4 million `int64` values which takes 32MB of space, this matches the output message.
2. The `cumprod` makes an additional 4 million `int64` array which is another 32MB of space bringing the total to 64MB which matches the memory usage statement after `efunc cumsum id_1`

**Comment by glitch** [comment]
Looking at @ronawho 's comparison I think I see where the 4x is coming from.  Assuming everything is using `int64`.

For the `scanPerf` output it has 400mil * 8bytes = 3.2G for the intial array.  This is spread over 4 nodes so the memory used per node is 3.2/4 or 0.8G.  It was noted that a copy is being made so it uses 2X the space; `0.8 + 0.8(for the copy)` = 1.6G for a single node which matches the `scanPerf` output.

Now for Arkouda, the memory output statement is in `arkouda_server.chpl` [417](https://github.com/Bears-R-Us/arkouda/blob/6ecd185cb695a13c3b5e43e3d6e80285e7afd9c5/src/arkouda_server.chpl#L417).   Briefly:
```
"bytes of memory used after command %t".format(getMemUsed():uint * numLocales:uint));
```
It looks like the arkouda example was also run on 4 nodes (`-nl 4`).  Since arkouda is accounting for memory on all of the nodes and there are 4 nodes, it makes sense the amount looks 4 times bigger.

**Comment by ronawho** [comment]
Oh, that's interesting. Both the chapel and arkouda examples should be using int64. On the chapel side the allocation high water mark is reported per locale, and I was assuming arkouda did the same, but I think you're right that arkouda is reporting the high water mark across all locales. Or really it's taking high water mark of locale 0 times the number of locales.

**Comment by ronawho** [comment]
Ok, so with that in mind and running the arkouda version again with chapel memStats on, here's what I see:

```
./arkouda_server -nl 4 --memStats
python3 scan.py localhost 5555 $((10**8*4))
python3 util/test/shutdown.py localhost 5555

memStats: node 0 Allocation High Water Mark: 2400065220
```

So there's a 3x overhead for arkouda compared to the 2x for standalone chapel. And this makes sense because arkouda creates a symbol table entry ahead of time and then assigns the result of the scan into it, so there's an extra allocation:

https://github.com/Bears-R-Us/arkouda/blob/6ecd185cb695a13c3b5e43e3d6e80285e7afd9c5/src/EfuncMsg.chpl#L70-L73

**Comment by glitch** [comment]
That's interesting, so are you saying if we did something like this:
```
 when "cumprod" {
    var a = * scan e.a;
    st.addEntry(rname, new shared SymEntry(a));
}
```
we might be able to shave off one of the copies?

**Comment by bradcray** [comment]
I was wrestling with this question as well, and think it's worth a try, though I feel uncertain about our chances of success.  There are a few too many moving parts for me to predict what will happen.

Generally speaking in Chapel, if you have a function that returns an array (which is effectively what you can think of the scan expression as being):

```chapel
proc foo() {
  var X: [1..n] real;
  return X;
}
```

and you capture it into a new variable:

```chapel
var A: [1..n] real = foo();
```

`A` will "steal" the memory allocated for `X` (because `X` is clearly "dead" to the compiler once it's returned) rather than allocating its own memory and doing a deep copy of it.  So that made it seem promising to me that if we created the SymEntry from an existing array, we could similarly avoid an extra copy / buffer allocation.

However, a difference in Arkouda is that the `SymEntry` type itself stores an array field, and while the same principle may (and arguably should) apply in the event that the array passed to the initializer is dead and used within the initializer to initialize the field, I'm not as confident that the compiler will get everything right today.  If the way you wrote it didn't work, a slight variant that also might be interesting to try would be:

```chapel
when "cumprod" {
    st.addEntry(rname, new shared SymEntry(* scan e.a));
}
```

which obviously _should_ be equivalent, but makes the fact that the scan operations return value is dead a bit more clearer to the compiler.

If this weren't to work, I think it'd be worth us investigating further why it doesn't, or what it would take for it to work.

And another fallback that we could think about if it couldn't be made to work would be to support a variant of the scan expression which took the input array in as an argument.  E.g., imagine something like `scan(*, a.a, e.a);`

**Comment by glitch** [comment]
Oh yeah, I was thinking along the lines of your last idea as well ( `scan(*, a.a, e.a);` ) like a "scan into" function.
