### ISSUE TITLE
`ak.random_strings_uniform()` segfaults when `minlen == maxlen`

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#883]
Reproducer:

```python
s = ak.random_strings_uniform(8, 8, 100)
[segfault]
```

`minlen` and `maxlen` are python-style bounds, meaning `minlen` is inclusive but `maxlen` is exclusive, so the code should raise an error if `maxlen <= minlen` (currently, it only raises if `maxlen < minlen`).

**Comment by glitch** [comment]
I know the fix for this is pretty easy (limit the client) but I was curious what was actually going on server side.
In `RandArray.chpl.newRandStringsUniformLength` the fillInt(..) proc gets called after the `lengths` dist array allocation.  In `fillInt` we fill the array with random integers, absolute value them and then trim the size down _when_ `aMax > aMin`.  Since `aMax` and `aMin` are equal we never trim the values down.  When we return the value of `nBytes` is determined by summing the lengths values.  This ends up with a rather large value for `nBytes` which is used to allocate the next distributed array.  We can't allocate one that large and :boom:
