### ISSUE TITLE
investigate parallel application of regex to ak.Strings arrays

### ISSUE THREAD

**Issue by mhmerrill** [Bears-R-Us/arkouda#894]
Currently we only have string searches with string constants (`startswith`, `endswith`, `contains`, `peel`, `stick`). Investigate parallel application of regex to `ak.Strings` arrays. 

- Chapel includes Google's `re2` library.
- create a way to apply the regex in parallel to `ak.Strings`.
- create a way to capture results from a parallel application of regex in Arkouda `ak.pdarrays` or `ak.Strings`.
- it is ok to create a less flexible application of regex and less flexible to start with...

This might take several people to think about the problem and collaborate. So I am assigning @pierce314159 and @glitch.
Get advice from possibly @reuster986, @bradcray , and @hokiegeek2 .

Edit:
We are splitting this ticket up into a few separate issues with this serving as the parent issue
- [x] #909
- [x] #910
- [x] #911
- [x] #957

**Comment by glitch** [comment]
Just an update:
@pierce314159 and I have been discussing/designing the inclusion of this functionality to Arkouda. @pierce314159 has been doing the _heavy lifting_ so far and has a working implementation using the RE2 wrapper on the following functions:

- contains
- startswith
- endswith
- peel (stick?)
- flatten

We've done some internal review on the code and things are shaping up nicely.

**Comment by mhmerrill** [comment]
- `match` returns a `pdarray` of `boolean`

- `find` might need to return several `pdarrays` something like: `count_of_matches_per_string`,`start_of_match`,`end_of_match`

- `pslice` a new function which takes/uses output of `find`

**Comment by glitch** [comment]
After talking with @pierce314159 and reviewing some of the code changes and taking into account what @mhmerrill mentioned above we are thinking it might be a good idea to split this ticket up into a few separate issues.

- First issue to add in general RE2 calls where no new results are generated, just an option to use RE2 for some of the functions which generate boolean vectors (i.e. `contains`, `startswith`, `endswith`, etc.)
- Second issue to address `flatten` since it is a bit more complex than the boolean vector ones
- Third issue for `peel`?  Not sure if @pierce314159 already got that parallel implementation working, it may be similar in complexity to `flatten` and if it is not included in the first issue we can stand it up as its own.
- Fourth issue to figure out the proper internal behavior of `find` operation and what would need to be returned as mentioned in previous comment.  Addition of a `pslice` function to use the output of `find` etc.  (I'm curious if this would end up operating similar to `flatten`.  The splitting notion of `flatten` can be inverted to the _matching_ part of the regex (groups) ).

If breaking up the work like this seems like a good plan we can generate those tickets and soft-link them back to this one as a parent issue.

**Comment by mhmerrill** [comment]
I am ok with breaking this issue into several smaller/bite-sized issues ;-)

**Comment by bradcray** [comment]
FWIW (and at the risk of being pedantic), a technique we often use in cases like this on GitHub is to edit the OP of this issue, making it the "umbrella issue" for the effort, and having it refer to the sub-issues that were spawned out of it using a TODO list, like:

- [ ] add in general RE2 calls #12345
- [ ] address flatted #23456
- [ ] etc.

(where those issue numbers would become hyperlinks if I'd used real issue numbers...).  That way, the context of the discussion so far isn't lost and someone tracking this issue can find their way to the things that it spawned.

**Comment by pierce314159** [comment]
I've put up PR #912 which address the first task for this issue (#909 regex support `contains`, `startswtith`, `endswith`, `match`, and `peel`)

**Comment by pierce314159** [comment]
I've put PR #920 which address the second task for this issue (#910 regex support for `Strings.flatten`)

**Comment by pierce314159** [comment]
I've put up PR #927 which addresses the third task for this issue (#911 Implement `find` and `slice` on regexes for `Strings`)

**Comment by reuster986** [comment]
I think this is fulfilled -- good work @pierce314159 ! And thanks to @ronawho and @glitch for implementation guidance and @mhmerrill for getting the ball rolling! I just cut a new release (v2021.11.02) that includes this functionality.
