### ISSUE TITLE
Sort fails to sort under bizarre condition

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#937]
The `assert` below fails:

```python
L = -2**15
U = 2**16
a = ak.randint(L, U, 100)
assert ak.is_sorted(ak.sort(a))
```

Varying `L` and `U` leads to the following inferred conditions for triggering the bug:
 - `a.dtype == ak.int64` (The `assert` succeeds for `float64`)
 - `a` must contain both positive and negative values
 - `2**(n-1) <= a.max() < 2**n` where `n` is a multiple of 16. That is, the leading non-zero bit of the positive subset of `a` must be the 16th, 32nd, or 48th bit.
 - `-2**(n-1) <= a.min() < 0`. That is, the nth bit in the negative subset of `a` must not always be zero (in two's complement). 

I'm guessing that there is a bug in how negative integer values are handled in the LSD radix sort when the highest bit in the final digit is set for both positive and negative elements.

**Comment by ronawho** [comment]
Sorting negative values was optimized in https://github.com/Bears-R-Us/arkouda/pull/232, and I suspect that could be the source of problems especially given the digit boundary condition in bullet 3. I was worried about getting those optimizations right at the time so I added a pretty extensive test in https://github.com/Bears-R-Us/arkouda/pull/207, but apparently not extensive enough.

**Comment by ronawho** [comment]
Hardcoded test case:

```python
import arkouda as ak
import time, sys

ak.connect(server=sys.argv[1], port=sys.argv[2])

a = ak.array([1, -1, 32767]) # sorts ok
b = ak.array([1,  0, 32768]) # sorts ok
c = ak.array([1, -1, 32768]) # does not sort

assert ak.is_sorted(ak.sort(a))
assert ak.is_sorted(ak.sort(b))

sC = ak.sort(c)
if not ak.is_sorted(sC):
    print(sC.to_ndarray())
assert ak.is_sorted(sC)
```

Slight variant of your test case with multiple trials:

```python
import arkouda as ak
import sys

ak.connect(server=sys.argv[1], port=sys.argv[2])

L = -2**15
U = 2**16
for i in range(100):
    a = ak.randint(L, U, 100)
    sA = ak.sort(a)
    if not ak.is_sorted(sA):
        print(sA.to_ndarray())
    assert ak.is_sorted(sA)
```

**Comment by ronawho** [comment]
I _think_ the problem is that the current `getBitWidth` code considers the bit widths of positive and negative values independently. If you just have positive values up to `2**16` then you only need 16 bits. And if you only have negative values down to `-2**15` then you still only need 16 bits (15 for value, 1 for signbit.) However, if you have the values `2**16` and `-1`, we actually need 16 bits for values still, and then an additional one for the signbit. So I think we need to instead consider how many bits we need for values and a signbit.

I think the following accomplishes that:

```diff
diff --git a/src/RadixSortLSD.chpl b/src/RadixSortLSD.chpl
index 8c1156e..dd4936e 100644
--- a/src/RadixSortLSD.chpl
+++ b/src/RadixSortLSD.chpl
@@ -30,8 +30,9 @@ module RadixSortLSD
       var aMin = min reduce a;
       var aMax = max reduce a;
       var wPos = if aMax >= 0 then numBits(int) - clz(aMax) else 0;
-      var wNeg = if aMin < 0 then numBits(int) - clz((-aMin)-1) + 1 else 0;
-      const bitWidth = max(wPos, wNeg);
+      var wNeg = if aMin < 0 then numBits(int) - clz((-aMin)-1) else 0;
+      var signBit = if aMin < 0 then 1 else 0;
+      const bitWidth = max(wPos, wNeg) + signBit;
       const negs = aMin < 0;
       return (bitWidth, negs);
     }
```

That resolves these particular tests cases, but I'd like to think about this some more and consult @mppf before opening a PR.
