### ISSUE TITLE
Handle Regex deprecation warnings with Chapel 1.25.0

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#939]
All Chapel based unit tests fail when building Arkouda with Chapel 1.25.0 due to Regex deprecation warnings in std.out.  (Specifically, our expected output in the `.good` files for each test does not contain the deprecation warnings which cause the failure.)

We need to be both 1.24.x and 1.25.0 compatible for overlapping time periods so we need to handle building with both versions.

The most likely fix here is to follow the same path that was done for the Memory Diagnostic changes between versions 1.23.x and 1.24.x where the version specific imports are encapsulated in a module and a switch in the Makefile compiles the proper version based on the present Chapel version.

(See `ARKOUDA_COMPAT_MODULES` in makefile and merge commit https://github.com/Bears-R-Us/arkouda/commit/04f31447311cae05b2a77bd6fcc4f986d13e306d , PR https://github.com/Bears-R-Us/arkouda/pull/713 )

**Comment by ronawho** [comment]
A quick fix for this (to quiet the .good file mismatches) could be to throw `--no-warnings` in test/COMPOPTS.

Though longer term you will want to migrate to the updated API, so the compat modules makes sense too. I will note that for https://github.com/Bears-R-Us/arkouda/issues/917#issuecomment-921332166 I've been thinking we'll need to add a copy of Chapel's regex module to Arkouda to get some upcoming optimizations sooner than chapel 1.26, so that could also solve this by having an `ArkoudaRegex` module that uses the new API.
