### ISSUE TITLE
Warn about float precision on `GroupBy.aggregate(float64)`

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#964]
Because arkouda implements grouped aggregations as differences on scans, these operations can amplify floating point precision errors beyond what is typical in numpy/pandas. We should consider raising a warning when the user calls an aggregation on a `float64` pdarray. The warning message should be something like, "Grouped aggregations on float64 can magnify errors due to floating point imprecision."

We might also consider adding a section to the documentation on this issue, and linking to that page in the warning message.

Example:
```python
N = 10**8
G = 10**7
groupnum = ak.randint(0, G, N, seed=1)
intval = ak.randint(0, 2**32, N, seed=2)
floatval = ak.cast(intval, ak.float64)
g = ak.GroupBy(groupnum)
_, intmean = g.mean(intval) # Exact mean
_, floatmean = g.mean(floatval) # Approximate; WARN here
ak_mse = ak.mean((intmean - floatmean)**2)
print(ak_mse)
1.1131222...

df = pd.DataFrame()
df['groupnum'] = groupnum.to_ndarray()
df['intval'] = intval.to_ndarray()
df['floatval'] = floatval.to_ndarray()
gdf = df.groupby('groupnum').agg({'intval': 'mean', 'floatval': 'mean'})
pd_mse = ((gdf.intval - gdf.floatval)**2).mean()
print(pd_mse)
0.0
```

In this example, the mean squared error in arkouda between int and float results is on the order of 1, whereas the mse in pandas/numpy is 0 (below machine tolerance).

**Comment by reuster986** [comment]
Just came across [Kahan summation](https://en.wikipedia.org/wiki/Kahan_summation_algorithm), which would actually solve this problem (presumably).

**Comment by pierce314159** [comment]
I was looking into the Kahan summation a bit and it mentions [Pairwise Summation](https://en.wikipedia.org/wiki/Pairwise_summation) which seems like it might be a better fit.

from https://en.wikipedia.org/wiki/Kahan_summation_algorithm#Alternatives :
Although Kahan's algorithm achieves `O(1)` error growth for summing `n` numbers, only slightly worse `O(log n)` growth can be achieved by pairwise summation... This has the advantage of requiring the same number of arithmetic operations as the naive summation (unlike Kahan's algorithm, which requires four times the arithmetic and has a latency of four times a simple summation) and can be calculated in parallel.

**Comment by reuster986** [comment]
@pierce314159 I agree with you for summing an entire array, but `GroupBy.sum(x)` requires a scan (i.e. `cumsum`), not just a reduction. I don't see a straightforward way to implement a scan with pairwise summation (I could be wrong!), but I think Kahan would be pretty easy to write as a Chapel `ReduceScanOp` class. Even with 4x the arithmetic, I suspect the scan will still feel fast to the user, but I need to measure. More benchmarks!

**Comment by pierce314159** [comment]
@reuster986 I took a swing at a Kahan sum `ReduceScanOp` class. What I have makes the error worse (and is inconsistent between runs). I think is due to the `c` value being applied out of order. Since scans are data parallel, it's likely to have a different correction applied at each step than when ran serially

I think this might work itself out for a reduction since all the corrections get applied at some point[^1], but I'm pretty sure applying the corrections out of order messes up scan/cumsum. It's also very likely there's something wrong with my implementation since I've not played with `ReduceScanOp` classes before

The footnote is a bit over the top but I like it too much to change lol

[^1]: I'm actually not convinced of this because when ran serially the final correction never gets applied (so maybe reduction is fine as long as the last element of the list happens to be the last element summed?)

<details>
  <summary>Some of the code</summary>

My kahan scan class looks like this:
```C
class KahanReduceScanOp: ReduceScanOp {
  type eltType;
  var value: eltType;
  var c: eltType;

  proc identity return 0: eltType;

  proc accumulate(elm) { accumulateOntoState(value, elm); }

  proc accumulateOntoState(ref state, elm) {
    var y = elm - c;
    var t = state + y; 
    c = (t - state) - y;
    state = t;
  }

  proc combine(other: borrowed KahanReduceScanOp) { accumulateOntoState(value, other.value); }

  proc generate() return value;

  proc clone() return new unmanaged KahanReduceScanOp(eltType=eltType);
}
```
And I updated the `isFloatType(t)` condition of `segSum` to
```C
if isFloatType(t) {
  var arrCopy;
  if skipNan {
    arrCopy = [elem in values] if isnan(elem) then 0.0 else elem;
  }
  else {
    arrCopy = values;
  }
  cumsum = KahanReduceScanOp scan arrCopy;
}
```
</details>

**Comment by ronawho** [comment]
I believe this was resolved by https://github.com/Bears-R-Us/arkouda/pull/1055.
