### ISSUE TITLE
Tune `in1d` thresholds

### ISSUE THREAD

**Issue by reuster986** [Bears-R-Us/arkouda#970]
See discussion on #968 and #969 - assigning to @ronawho at his request. From his measurements, it looks like the `mbound` for `int64` is too high, at least for XC, and the `in1dAssocSortThreshold` for strings is too low. I wonder how different it looks between CS and XC...

**Comment by ronawho** [comment]
As part of this, we should think about better ways to sync the server/benchmark implementation strategy thresholds.

**Comment by ronawho** [comment]
16-node-cs-hdr testing has been down since Dec 13 (and we only started running this test in nightly on the 14 so this is the first time running) and it turns out int in1d is timing out for the `mbound` on CS.

The slow code is:
 https://github.com/Bears-R-Us/arkouda/blob/718b3f6e53286925089f9f7cde3b748b404c5def/src/In1d.chpl#L99-L100 
where the biggest issue for multi-locale and especially CS is that `ar2` is a block dist array so these are fine-grained GETs. We can improve this by doing bulk communication to localize to a local array first.

The second problem is that we're adding to the set serially. The `mbound` case is always faster than `lbound` when ran serially, but as the array size increases parallelism outweighs the cheaper implementation. On single node 24-core chapcs, `2**21` is faster for `mBound`, and `2**22` is slower. The current threshold is `2**25` so we at least want to go down 8x, but probably even more so when distributed and we have to localize and when there's more cores making the paralllel `lbound` code faster. 

```
>>> arkouda int64 in1d
Medium regime: numLocales = 1  a.size = 10,000,000  b.size = 4,194,303
Medium average time = 0.4440 sec
Medium average rate = 0.24 GiB/sec
Large regime: numLocales = 1  a.size = 10,000,000  b.size = 4,194,305
Large average time = 0.3926 sec
Large average rate = 0.27 GiB/sec
```

I'm wondering if it's even worth optimizing based on array size or if we should always just use the `lbound` implementation. On single node you're talking about saving maybe 0.1 seconds in the best case, though it's higher at scale for multi-locale because the startup cost for sort is much higher. Even if it is faster at scale, do you think in1d with a small second array is a common enough to be worth maintaining the additional code?

**Comment by ronawho** [comment]
And a reminder that sort does have a non-trivial startup cost based on the total number of cores. At 75K cores we saw ~20 seconds of startup time in some previous runs:

![apollo-sort-scale](https://user-images.githubusercontent.com/1588337/148950793-812f91ca-fbcc-4ed5-92de-41df26ce2e16.png)

So at extreme scale `mbound` is probably faster, but I'm still not sure if it's worth optimizing that case or not. Happy to do it if you think it's common enough to warrant it, but it would simplify code and reasoning about performance to just go with a single implementation (and note that at the moment I'm only talking about doing this for the int case, haven't looked at string yet.)

**Comment by ronawho** [comment]
Eh, even the `mbound` approach has scalability issues with trying to localize the second array. 

Here's a patch that tries a couple difference schemes to improve that:

<details>

```diff
diff --git a/src/In1d.chpl b/src/In1d.chpl
index a0288b7..ad9f8e1 100644
--- a/src/In1d.chpl
+++ b/src/In1d.chpl
@@ -60,6 +60,17 @@ module In1d
         return truth;
     }

+    iter offset(r: range) {
+      for i in r + (r.size/numLocales * here.id) do {
+        yield i % r.size + r.first;
+      }
+    }
+
+    iter offset(param tag: iterKind, r: range) where (tag==iterKind.standalone) {
+      forall i in r + (r.size/numLocales * here.id) do {
+        yield i % r.size + r.first;
+      }
+    }
     /* Put ar2 into an associative domain of int, per locale.
     Creates truth (boolean array) from the domain of ar1.
     ar1 and truth are distributed on the same locales.
@@ -79,6 +90,9 @@ module In1d
     :returns truth: the distributed boolean array containing the result of ar1 being broadcast over ar2
     :type truth: [] bool
     */
+    enum In1dAr2PerLocAssocStategy { FineGrainedGet, BulkArrCopy, AggArrGather, OffsetAggArrGather, OffsetLocalizingSlice };
+    use In1dAr2PerLocAssocStategy;
+    config const in1dAr2PerLocAssocStategy = In1dAr2PerLocAssocStategy.FineGrainedGet;
     proc in1dAr2PerLocAssoc(ar1: [?aD1] int, ar2: [?aD2] int) {

         var truth: [aD1] bool;
@@ -93,14 +107,52 @@ module In1d

                 var ar2Set: domain(int, parSafe=false); // create a set to hold ar2, parSafe modification is OFF
                 ar2Set.requestCapacity(ar2.size); // request a capacity for the initial set
-
-                if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] = t.elapsed(); t.clear(); t.start();}
-
-                // serially add all elements of ar2 to ar2Set
-                for e in ar2 { ar2Set += e; }
-                // all elements of ar2 have been added to ar2Set so modification done.
-
-                if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] = t.elapsed(); t.clear(); t.start();}
+                select (in1dAr2PerLocAssocStategy) {
+                  // Fine-grained GET
+                  when FineGrainedGet {
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] = t.elapsed(); t.clear(); t.start();}
+                    for e in ar2 { ar2Set += e; }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] = t.elapsed(); t.clear(); t.start();}
+                  }
+                  // Bulk array assignment (seems to timeout, not sure why)
+                  when BulkArrCopy {
+                    var lar2: [aD2.low..aD2.high] int = ar2;
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] = t.elapsed(); t.clear(); t.start();}
+                    for e in lar2 { ar2Set += e; }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] = t.elapsed(); t.clear(); t.start();}
+                  }
+                  // Aggregated array gather
+                  when AggArrGather {
+                    var lar2: [aD2.low..aD2.high] int;
+                    forall (l, r) in zip(lar2, ar2) with (var agg = newSrcAggregator(int)) {
+                      agg.copy(l, r);
+                    }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] = t.elapsed(); t.clear(); t.start();}
+                    for e in lar2 { ar2Set += e; }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] = t.elapsed(); t.clear(); t.start();}
+                  }
+                  // Offset aggregated array gather (avoid lockstep comm)
+                  when OffsetAggArrGather {
+                    var lar2: [aD2.low..aD2.high] int;
+                    forall i in offset(aD2.low..aD2.high) with (var agg = newSrcAggregator(int)) {
+                      agg.copy(lar2[i], ar2[i]);
+                    }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] = t.elapsed(); t.clear(); t.start();}
+                    for e in lar2 { ar2Set += e; }
+                    if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] = t.elapsed(); t.clear(); t.start();}
+                  }
+                  // Offset localizing slices (more optimized bulk comm)
+                  when OffsetLocalizingSlice {
+                    use AryUtil;
+                    for loc in offset(0..<numLocales) {
+                      var lD = ar2.localSubdomain(Locales[loc]);
+                      var slice = new lowLevelLocalizingSlice(ar2, lD.low..lD.high);
+                      if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][0] += t.elapsed(); t.clear(); t.start();}
+                      for i in 0..<lD.size { ar2Set += slice.ptr[i]; }
+                      if logLevel == LogLevel.DEBUG {t.stop(); timings[here.id][1] += t.elapsed(); t.clear(); t.start();}
+                    }
+                  }
+                }

                 // in parallel check all elements of ar1 to see if ar2Set contains them
                 [i in truth.localSubdomain()] truth[i] = ar2Set.contains(ar1[i]);
```

</details>

And here's performance for `./benchmarks/run_benchmarks.py in1d -nl 512` on 512 nodes of a Cray XC for `2**25 +- 1`.

`mbound` perf for different strategies in the above diff:

| Stategy               | Performance | Time  |
| --------------------- | ----------: | ----: |
| FineGrainedGet        | 0.41 GB/s   | 93.9s |
| AggArrGather          | 1.67 GB/s   | 22.8s |
| OffsetAggArrGather    | 2.21 GB/s   | 17.4s |
| OffsetLocalizingSlice | 6.44 GB/s   |  5.9s |

And the `lbound` perf

| Stategy               | Performance | Time  |
| --------------------- | ----------: | ----: |
| SortScheme            | 4.12 GB/s   |  7.4s |

---

And dropping `mbound` to `2**22` and changing the problem size to `2**22 +- 1` we see that `mbound` is more of a win a smaller problem sizes:

| Stategy               | Performance | Time  |
| --------------------- | ----------: | ----: |
| OffsetLocalizingSlice | 53.3 GB/s   |  0.7s |
| SortScheme            |  5.2 GB/s   |  7.2s |

So can still be worthwhile if you think smaller in1d operations are frequent enough for the perf win to be worthwhile.

**Comment by reuster986** [comment]
Thanks for running these experiments!

Regarding your question about whether in1d with small/medium ar2 are frequent enough to be worth a dedicated strategy, I would like to gather some metrics from user logs, but my intuition is that yes, they are quite frequent. It's fairly common to check a large array for membership in a curated set of hundreds or thousands of objects. I'll try to get those numbers, but I do think having a separate case is worthwhile.

**Comment by ronawho** [comment]
Ok, that's good enough for me. I'll work on optimizing the `mBound` case. Do you also see value in the very tiny `2**4` `sBound` case?

**Comment by reuster986** [comment]
I do think it's somewhat common do run in1d with very tiny ar2 (as a more compact way to write `(a == val1) | (a == val2) | ... | (a == valn)` for a short list of literals), but I don't know if the performance of the small strategy is actually better than the medium strategy at that size.

**Comment by ronawho** [comment]
Right, I'm not sure what the performance is like either, but I wanted to see if it's worth experimenting and tuning that performance too. I'll add that to the list of experiments to do.

**Comment by ronawho** [comment]
https://github.com/Bears-R-Us/arkouda/pull/1044 switches to the `OffsetLocalizingSlice` slice strategy and removes the `sBound` code since it's never faster than this new optimized `mBound` scheme. Copying from that PR:

"""
Here's some performance figures for various second array sizes on 16-node-cs-hdr before and after (first array size of `10**8`)

| Size      | Before      | Now         |
| --------- | ----------: | ----------: |
| 2**1      | 316.2 GiB/s | 324.7 GiB/s |
| 2**4      |  90.8 GiB/s | 250.1 GiB/s |
| 2**8      | 208.4 GiB/s | 247.3 GiB/s |
| 2**16     |  47.3 GiB/s | 177.3 GiB/s |
| 2**22     |   0.9 GiB/s |   9.4 GiB/s |
| 2**23     |   0.4 GiB/s |   4.8 GiB/s |
| 2**24     |   0.2 GiB/s |   2.5 GiB/s |
| 2**25 - 1 |   0.1 GiB/s |   1.3 GiB/s |
| 2**25 + 1 |   4.2 GiB/s |   4.2 GiB/s |

So overall some large performance benefits, though we'll probably still want to do some tuning on the threshold between the medium and large strategy.

Given that the medium size is doing an all gather, I wanted to check scaling too. Here's some 512-node-xc results:

| Size      | Before      | Now         |
| --------- | ----------: | ----------: |
| 2**25 - 1 |   0.4 GiB/s |   6.4 GiB/s |
| 2**25 + 1 |   4.1 GiB/s |   4.1 GiB/s |

So here we still see improved performance for the set strategy, and in this case it's actually faster than the sort strategy at the current threshold.

The main bottleneck in the set strategy is that we're serially adding to a set and this serialization becomes more apparent on higher core count machines. It's unlikely that we'll be able to come up with a perfect simple threshold because it depends on core count and network speed, but I would still lean towards dropping it to `2**22` or `2**23` or so.

This threshold is also optimization dependent and there's likely more we can do to optimize both strategies. Chapel should eventually have a portable and scalable concurrent set which would help with the current serialization. I haven't looked at tuning the sort-based strategy at all yet but there is likely room for improvement. In the end, I don't think we need a prefect threshold and I lean towards lowering the sort threshold because sort is used for so much else it has well known performance behavior.
"""

So my inclination is to merge that PR, take a quick look at optimizing the sort-based strategy, and then lower the threshold for when we use the sort-based strategy for int in1d.

Then after that take a quick look at the code and threshold for strings, which I haven't looked at yet.

**Comment by ronawho** [comment]
@reuster986 while looking to optimize the string version, I found the hash based string code looked very similar to the numeric code. Is there any reason that the string hash version can't just call the int version. Something like `in1d(mainStr.hash(), testStr.hash())`?

Prototype code is in https://github.com/Bears-R-Us/arkouda/commit/e0a32ac87895dd7c731eab4c189abfb830726612

**Comment by ronawho** [comment]
Small/Medium sized int in1d ops were optimized in https://github.com/Bears-R-Us/arkouda/pull/1044. 

Large sized int in1d ops were optimized in https://github.com/Bears-R-Us/arkouda/pull/1063 and https://github.com/Bears-R-Us/arkouda/pull/1125 and the threshold was tuned in https://github.com/Bears-R-Us/arkouda/pull/1131

The string in1d ops were switched to use the int version in https://github.com/Bears-R-Us/arkouda/pull/1132, so we get all the optimizations/tuning benefits that we did for ints for free here.

I don't think there is any low-hanging optimization work remaining and the thresholds have been tuned, so think this is good to close.
