### ISSUE TITLE
UnitTestParquetCpp.chpl fails when Parquet not built

### ISSUE THREAD

**Issue by glitch** [Bears-R-Us/arkouda#989]
Running the Chapel-based unit tests, `UnitTestParquetCpp.chpl` fails when the optional Parquet/Arrow code is not built

Example output:
```
[Executing diff UnitTestParquetCpp.good UnitTestParquetCpp.1.comp.out.tmp]
0a1,2
> projects/arkouda//src/Parquet.chpl:6: error: opening projects/arkouda//src/ArrowFunctions.o: No such file or directory
> Note: This source location is a guess.
[Error matching compiler output for projects/arkouda/test/UnitTestParquetCpp]
```

I believe we need to skip the test if Parquet support is not present.
Steps to reproduce
- Remove `ArrowFunctions.o` if it exists
- Make sure `ARKOUDA_SERVER_PARQUET_SUPPORT` is unset
- `start_test test/UnitTestParquetCpp.chpl` or `start_test test/`

**Comment by ronawho** [comment]
Hmm, I thought the [skipif](https://github.com/Bears-R-Us/arkouda/blob/master/test/UnitTestParquetCpp.skipif) would skip this test if parquet support was not detected. Note that if you explicitly specify a file on the command line, `start_test` will run that and ignore skipifs since we're assuming if you explicitly listed it, you want it tested. I would expect the `start_test test/` version to auto-skip though.

**Comment by ronawho** [comment]
Here's what I see for the `start_test test` version:


```sh
rm -rf test/
git checkout test/COMPOPTS test/UnitTestParquet* test/TestBase*

start_test test/
> ...
> [test: /Users/eronagha/Desktop/arkouda/test/UnitTestParquetCpp.chpl]
> [Skipping test based on .skipif environment settings: /Users/eronagha/Desktop/arkouda/test/UnitTestParquetCpp]
> ...
```

**Comment by glitch** [comment]
Hmm.. I think I may have been in a weird state when this happened.  Master builds fine without parquet, I think I may have actually run this with my parallel test script which invoked it manually (ala start_test test/UnitTest...) so what you said makes sense.  I'm going to close the issue as moot.
